#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

	void yyerror(char* s);
	int yylex();
	#include "stdio.h"
	#include "stdlib.h"
	#include "ctype.h"
	#include "string.h"
	void insert_type();
	void insert_value();
	void insert_dimensions();
	void insert_parameters();
	void remove_scope (int );
	int check_scope(char*);
	int check_function(char *);
	void insert_SymbolTable_nest(char*, int);
	void insert_SymbolTable_paramscount(char*, int);
	int getSTparamscount(char*);
	int check_duplicate(char*);
	int check_declaration(char*, char *);
	int check_params(char*);
	int duplicate(char *s);
	int check_array(char*);
	void insert_SymbolTable_function(char*);
	char gettype(char*,int);

	struct ErrorTableNode {

		int line_number;
		char *error_message;
		struct ErrorTableNode *next;

	};
	typedef struct ErrorTableNode ErrorTableNode;

	ErrorTableNode *error_table[1];

	extern void print_error_table();
	extern void insert_error_table(int line_number, char *error_message);
	extern void init_error_table();

	int insert_flag = 0;

	extern char current_identifier[20];
	extern char current_type[20];
	extern char current_value[20];
    extern char current_function[20];
	extern char previous_operator[20];
	extern int current_nested_val;
	char currfunctype[100];
	char currfunccall[100];
	extern int params_count;
	int call_params_count;
	int arr_dim = 0;


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	DOUBLE	262
#define	LONG	263
#define	SHORT	264
#define	SIGNED	265
#define	UNSIGNED	266
#define	STRUCT	267
#define	RETURN	268
#define	MAIN	269
#define	VOID	270
#define	WHILE	271
#define	FOR	272
#define	DO	273
#define	BREAK	274
#define	CONTINUE	275
#define	GOTO	276
#define	ENDIF	277
#define	SWITCH	278
#define	CASE	279
#define	DEFAULT	280
#define	identifier	281
#define	array_identifier	282
#define	integer_constant	283
#define	string_constant	284
#define	float_constant	285
#define	character_constant	286
#define	ELSE	287
#define	MOD_EQUAL	288
#define	MULTIPLY_EQUAL	289
#define	DIVIDE_EQUAL	290
#define	ADD_EQUAL	291
#define	SUBTRACT_EQUAL	292
#define	OR_OR	293
#define	AND_AND	294
#define	EQUAL	295
#define	NOT_EQUAL	296
#define	LESS_EQUAL	297
#define	LESS	298
#define	GREAT_EQUAL	299
#define	GREAT	300
#define	SIZEOF	301
#define	NOT	302
#define	INCREMENT	303
#define	DECREMENT	304


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int LONG;
static const int SHORT;
static const int SIGNED;
static const int UNSIGNED;
static const int STRUCT;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int DO;
static const int BREAK;
static const int CONTINUE;
static const int GOTO;
static const int ENDIF;
static const int SWITCH;
static const int CASE;
static const int DEFAULT;
static const int identifier;
static const int array_identifier;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int MOD_EQUAL;
static const int MULTIPLY_EQUAL;
static const int DIVIDE_EQUAL;
static const int ADD_EQUAL;
static const int SUBTRACT_EQUAL;
static const int OR_OR;
static const int AND_AND;
static const int EQUAL;
static const int NOT_EQUAL;
static const int LESS_EQUAL;
static const int LESS;
static const int GREAT_EQUAL;
static const int GREAT;
static const int SIZEOF;
static const int NOT;
static const int INCREMENT;
static const int DECREMENT;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,DOUBLE=262
	,LONG=263
	,SHORT=264
	,SIGNED=265
	,UNSIGNED=266
	,STRUCT=267
	,RETURN=268
	,MAIN=269
	,VOID=270
	,WHILE=271
	,FOR=272
	,DO=273
	,BREAK=274
	,CONTINUE=275
	,GOTO=276
	,ENDIF=277
	,SWITCH=278
	,CASE=279
	,DEFAULT=280
	,identifier=281
	,array_identifier=282
	,integer_constant=283
	,string_constant=284
	,float_constant=285
	,character_constant=286
	,ELSE=287
	,MOD_EQUAL=288
	,MULTIPLY_EQUAL=289
	,DIVIDE_EQUAL=290
	,ADD_EQUAL=291
	,SUBTRACT_EQUAL=292
	,OR_OR=293
	,AND_AND=294
	,EQUAL=295
	,NOT_EQUAL=296
	,LESS_EQUAL=297
	,LESS=298
	,GREAT_EQUAL=299
	,GREAT=300
	,SIZEOF=301
	,NOT=302
	,INCREMENT=303
	,DECREMENT=304


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::DOUBLE=262;
const int YY_parse_CLASS::LONG=263;
const int YY_parse_CLASS::SHORT=264;
const int YY_parse_CLASS::SIGNED=265;
const int YY_parse_CLASS::UNSIGNED=266;
const int YY_parse_CLASS::STRUCT=267;
const int YY_parse_CLASS::RETURN=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::VOID=270;
const int YY_parse_CLASS::WHILE=271;
const int YY_parse_CLASS::FOR=272;
const int YY_parse_CLASS::DO=273;
const int YY_parse_CLASS::BREAK=274;
const int YY_parse_CLASS::CONTINUE=275;
const int YY_parse_CLASS::GOTO=276;
const int YY_parse_CLASS::ENDIF=277;
const int YY_parse_CLASS::SWITCH=278;
const int YY_parse_CLASS::CASE=279;
const int YY_parse_CLASS::DEFAULT=280;
const int YY_parse_CLASS::identifier=281;
const int YY_parse_CLASS::array_identifier=282;
const int YY_parse_CLASS::integer_constant=283;
const int YY_parse_CLASS::string_constant=284;
const int YY_parse_CLASS::float_constant=285;
const int YY_parse_CLASS::character_constant=286;
const int YY_parse_CLASS::ELSE=287;
const int YY_parse_CLASS::MOD_EQUAL=288;
const int YY_parse_CLASS::MULTIPLY_EQUAL=289;
const int YY_parse_CLASS::DIVIDE_EQUAL=290;
const int YY_parse_CLASS::ADD_EQUAL=291;
const int YY_parse_CLASS::SUBTRACT_EQUAL=292;
const int YY_parse_CLASS::OR_OR=293;
const int YY_parse_CLASS::AND_AND=294;
const int YY_parse_CLASS::EQUAL=295;
const int YY_parse_CLASS::NOT_EQUAL=296;
const int YY_parse_CLASS::LESS_EQUAL=297;
const int YY_parse_CLASS::LESS=298;
const int YY_parse_CLASS::GREAT_EQUAL=299;
const int YY_parse_CLASS::GREAT=300;
const int YY_parse_CLASS::SIZEOF=301;
const int YY_parse_CLASS::NOT=302;
const int YY_parse_CLASS::INCREMENT=303;
const int YY_parse_CLASS::DECREMENT=304;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		241
#define	YYFLAG		-32768
#define	YYNTBASE	65

#define YYTRANSLATE(x) ((unsigned)(x) <= 304 ? yytranslate[x] : 144)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    52,     2,     2,    63,
    64,    50,    48,    60,    49,     2,    51,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    59,     2,
    38,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    61,     2,    62,    41,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    57,     2,    58,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    39,    40,    42,    43,    44,    45,    46,    47,
    53,    54,    55,    56
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     6,     8,    10,    12,    14,    15,    23,
    26,    27,    31,    33,    37,    40,    43,    44,    45,    49,
    50,    54,    56,    57,    61,    64,    65,    66,    71,    72,
    76,    77,    82,    84,    86,    87,    88,    92,    93,    99,
   102,   105,   106,   108,   110,   112,   114,   117,   120,   123,
   126,   128,   130,   133,   136,   137,   139,   142,   145,   146,
   148,   149,   151,   152,   155,   159,   163,   164,   168,   169,
   172,   175,   176,   177,   181,   184,   185,   187,   189,   191,
   193,   195,   197,   199,   200,   205,   208,   209,   212,   214,
   215,   223,   226,   227,   228,   235,   236,   245,   246,   255,
   257,   260,   262,   265,   269,   272,   276,   280,   284,   288,
   292,   296,   299,   302,   304,   308,   310,   314,   316,   319,
   321,   325,   327,   329,   331,   333,   335,   337,   339,   343,
   345,   347,   349,   353,   355,   357,   359,   361,   363,   365,
   367,   368,   374,   378,   380,   382,   383,   389,   391,   392,
   393,   397,   398,   403,   404,   406,   408,   410
};

static const short yyrhs[] = {    66,
     0,    67,    66,     0,     0,    71,     0,    97,     0,    68,
     0,     1,     0,     0,    12,    26,    69,    57,    70,    58,
    59,     0,    71,    70,     0,     0,    92,    73,    59,     0,
    72,     0,    12,    26,    73,     0,    75,    74,     0,    60,
    73,     0,     0,     0,    26,    76,    78,     0,     0,    27,
    77,    78,     0,    80,     0,     0,    38,    79,   123,     0,
    61,    81,     0,     0,     0,    28,    62,    82,    85,     0,
     0,    62,    83,    86,     0,     0,    28,    62,    84,    80,
     0,    86,     0,    88,     0,     0,     0,    38,    87,    29,
     0,     0,    38,    89,    57,    90,    58,     0,    28,    91,
     0,    60,    90,     0,     0,     4,     0,     5,     0,     6,
     0,     7,     0,     8,    95,     0,     9,    96,     0,    11,
    93,     0,    10,    94,     0,    15,     0,     4,     0,     8,
    95,     0,     9,    96,     0,     0,     4,     0,     8,    95,
     0,     9,    96,     0,     0,     4,     0,     0,     4,     0,
     0,    98,    99,     0,    92,    26,    63,     0,   100,    64,
   107,     0,     0,    92,   101,   102,     0,     0,   104,   103,
     0,    60,   100,     0,     0,     0,    26,   105,   106,     0,
    61,    62,     0,     0,   111,     0,   108,     0,   112,     0,
   115,     0,   120,     0,   121,     0,    71,     0,     0,   109,
    57,   110,    58,     0,   107,   110,     0,     0,   122,    59,
     0,    59,     0,     0,     3,    63,   123,    64,   113,   107,
   114,     0,    32,   107,     0,     0,     0,    16,    63,   123,
    64,   116,   107,     0,     0,    17,    63,   119,   123,    59,
   117,   122,    64,     0,     0,    18,   107,    16,    63,   123,
    64,   118,    59,     0,    71,     0,   122,    59,     0,    59,
     0,    13,    59,     0,    13,   122,    59,     0,    19,    59,
     0,   133,    38,   122,     0,   133,    36,   122,     0,   133,
    37,   122,     0,   133,    34,   122,     0,   133,    35,   122,
     0,   133,    33,   122,     0,   133,    55,     0,   133,    56,
     0,   123,     0,   123,    39,   124,     0,   124,     0,   124,
    40,   125,     0,   125,     0,    54,   125,     0,   126,     0,
   126,   127,   128,     0,   128,     0,    46,     0,    44,     0,
    47,     0,    45,     0,    42,     0,    43,     0,   128,   129,
   130,     0,   130,     0,    48,     0,    49,     0,   130,   131,
   132,     0,   132,     0,    50,     0,    51,     0,    52,     0,
   135,     0,   133,     0,    26,     0,     0,    27,   134,    61,
   122,    62,     0,    63,   122,    64,     0,   136,     0,   143,
     0,     0,    26,    63,   137,   138,    64,     0,   139,     0,
     0,     0,   122,   140,   141,     0,     0,    60,   122,   142,
   141,     0,     0,    28,     0,    29,     0,    30,     0,    31,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    93,    96,    97,   101,   102,   103,   104,   107,   107,   109,
   109,   112,   113,   116,   119,   122,   123,   126,   129,   129,
   129,   131,   131,   131,   134,   135,   138,   138,   139,   139,
   140,   140,   143,   144,   145,   148,   148,   151,   151,   154,
   157,   158,   162,   162,   162,   162,   163,   164,   165,   166,
   167,   170,   170,   170,   170,   173,   173,   173,   173,   176,
   176,   179,   179,   182,   185,   188,   191,   191,   191,   194,
   197,   198,   201,   201,   204,   205,   208,   208,   209,   209,
   210,   210,   211,   214,   214,   217,   218,   221,   222,   225,
   225,   228,   229,   232,   233,   233,   233,   234,   234,   237,
   238,   239,   242,   243,   256,   260,   268,   274,   281,   287,
   293,   300,   301,   302,   307,   308,   311,   312,   315,   316,
   319,   320,   323,   324,   325,   326,   327,   328,   331,   332,
   335,   336,   339,   340,   343,   343,   343,   346,   347,   350,
   360,   360,   368,   369,   370,   373,   378,   390,   390,   393,
   393,   396,   397,   397,   400,   401,   402,   403
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","DOUBLE","LONG","SHORT","SIGNED","UNSIGNED","STRUCT","RETURN",
"MAIN","VOID","WHILE","FOR","DO","BREAK","CONTINUE","GOTO","ENDIF","SWITCH",
"CASE","DEFAULT","identifier","array_identifier","integer_constant","string_constant",
"float_constant","character_constant","ELSE","MOD_EQUAL","MULTIPLY_EQUAL","DIVIDE_EQUAL",
"ADD_EQUAL","SUBTRACT_EQUAL","'='","OR_OR","AND_AND","'^'","EQUAL","NOT_EQUAL",
"LESS_EQUAL","LESS","GREAT_EQUAL","GREAT","'+'","'-'","'*'","'/'","'%'","SIZEOF",
"NOT","INCREMENT","DECREMENT","'{'","'}'","';'","','","'['","']'","'('","')'",
"begin_parse","declarations","declaration","structure_dec","@1","structure_content",
"variable_dec","structure_initialize","variables","multiple_variables","identifier_name",
"@2","@3","extended_identifier","@4","array_iden","array_dims","@5","@6","@7",
"initilization","string_initilization","@8","array_initialization","@9","array_values",
"multiple_array_values","datatype","unsigned_grammar","signed_grammar","long_grammar",
"short_grammar","function_dec","function_datatype","function_parameters","parameters",
"@10","all_parameter_identifiers","multiple_parameters","parameter_identifier",
"@11","extended_parameter","statement","multiple_statement","@12","statments",
"expression_statment","conditional_statements","@13","extended_conditional_statements",
"iterative_statements","@14","@15","@16","for_initialization","return_statement",
"break_statement","expression","simple_expression","and_expression","unary_relation_expression",
"regular_expression","relational_operators","sum_expression","sum_operators",
"term","MULOP","factor","mutable","@17","immutable","call","@18","arguments",
"arguments_list","@19","A","@20","constant",""
};
#endif

static const short yyr1[] = {     0,
    65,    66,    66,    67,    67,    67,    67,    69,    68,    70,
    70,    71,    71,    72,    73,    74,    74,    76,    75,    77,
    75,    78,    79,    78,    80,    80,    82,    81,    83,    81,
    84,    81,    85,    85,    85,    87,    86,    89,    88,    90,
    91,    91,    92,    92,    92,    92,    92,    92,    92,    92,
    92,    93,    93,    93,    93,    94,    94,    94,    94,    95,
    95,    96,    96,    97,    98,    99,   101,   100,   100,   102,
   103,   103,   105,   104,   106,   106,   107,   107,   107,   107,
   107,   107,   107,   109,   108,   110,   110,   111,   111,   113,
   112,   114,   114,   116,   115,   117,   115,   118,   115,   119,
   119,   119,   120,   120,   121,   122,   122,   122,   122,   122,
   122,   122,   122,   122,   123,   123,   124,   124,   125,   125,
   126,   126,   127,   127,   127,   127,   127,   127,   128,   128,
   129,   129,   130,   130,   131,   131,   131,   132,   132,   133,
   134,   133,   135,   135,   135,   137,   136,   138,   138,   140,
   139,   142,   141,   141,   143,   143,   143,   143
};

static const short yyr2[] = {     0,
     1,     2,     0,     1,     1,     1,     1,     0,     7,     2,
     0,     3,     1,     3,     2,     2,     0,     0,     3,     0,
     3,     1,     0,     3,     2,     0,     0,     4,     0,     3,
     0,     4,     1,     1,     0,     0,     3,     0,     5,     2,
     2,     0,     1,     1,     1,     1,     2,     2,     2,     2,
     1,     1,     2,     2,     0,     1,     2,     2,     0,     1,
     0,     1,     0,     2,     3,     3,     0,     3,     0,     2,
     2,     0,     0,     3,     2,     0,     1,     1,     1,     1,
     1,     1,     1,     0,     4,     2,     0,     2,     1,     0,
     7,     2,     0,     0,     6,     0,     8,     0,     8,     1,
     2,     1,     2,     3,     2,     3,     3,     3,     3,     3,
     3,     2,     2,     1,     3,     1,     3,     1,     2,     1,
     3,     1,     1,     1,     1,     1,     1,     1,     3,     1,
     1,     1,     3,     1,     1,     1,     1,     1,     1,     1,
     0,     5,     3,     1,     1,     0,     5,     1,     0,     0,
     3,     0,     4,     0,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
     7,    43,    44,    45,    46,    61,    63,    59,    55,     0,
    51,     1,     0,     6,     4,    13,     0,     5,    69,    60,
    47,    62,    48,    56,    61,    63,    50,    52,    61,    63,
    49,     8,     2,    18,    20,     0,    17,    67,    64,     0,
    57,    58,    53,    54,    18,     0,    14,    65,    26,    26,
    12,     0,    15,     0,    84,    11,    23,     0,    19,    22,
    21,    16,    73,    68,    72,     0,     0,     0,     0,     0,
    84,     0,   140,   141,   155,   156,   157,   158,     0,    89,
     0,    83,     0,    66,    78,     0,    77,    79,    80,    81,
    82,     0,   114,   116,   118,   120,   122,   130,   134,   139,
   138,   144,   145,     0,    11,     0,     0,    29,    25,    76,
    69,    70,     0,     0,   103,     0,     0,     0,     0,   105,
   146,     0,   119,   139,     0,    84,    88,     0,     0,   127,
   128,   124,   126,   123,   125,     0,   131,   132,     0,   135,
   136,   137,     0,     0,     0,     0,     0,     0,     0,   112,
   113,     0,    10,    24,    27,     0,     0,    74,    71,     0,
   104,     0,   102,   100,     0,     0,     0,   149,     0,   143,
    84,     0,   115,   117,   121,   129,   133,   111,   109,   110,
   107,   108,   106,     9,    35,    26,    36,    30,    75,    90,
    94,     0,   101,     0,   150,     0,   148,     0,    86,    85,
    36,    28,    33,    34,    32,     0,    84,    84,    96,     0,
   154,   147,   142,     0,    37,    93,    95,     0,    98,     0,
   151,     0,    84,    91,     0,     0,   152,    42,     0,    92,
    97,    99,   154,     0,    40,    39,   153,    41,     0,     0,
     0
};

static const short yydefgoto[] = {   239,
    12,    13,    14,    46,   104,    82,    16,    36,    53,    37,
    49,    50,    59,   106,    60,   109,   185,   156,   186,   202,
   188,   206,   204,   214,   229,   235,    83,    31,    27,    21,
    23,    18,    19,    39,    40,    54,    64,   112,    65,   110,
   158,   171,    85,    86,   172,    87,    88,   207,   224,    89,
   208,   218,   226,   165,    90,    91,    92,    93,    94,    95,
    96,   136,    97,   139,    98,   143,    99,   100,   122,   101,
   102,   168,   196,   197,   211,   221,   233,   103
};

static const short yypact[] = {   248,
-32768,-32768,-32768,-32768,-32768,     7,    19,    29,    52,     2,
-32768,-32768,   248,-32768,-32768,-32768,    -6,-32768,   288,-32768,
-32768,-32768,-32768,-32768,     7,    19,-32768,-32768,     7,    19,
-32768,    23,-32768,   -24,-32768,    -4,    -2,-32768,-32768,   -34,
-32768,-32768,-32768,-32768,-32768,     6,-32768,-32768,   -13,   -13,
-32768,    23,-32768,    39,   178,   276,-32768,   -15,-32768,-32768,
-32768,-32768,-32768,-32768,    13,    14,    53,    15,    24,    40,
   178,    48,    45,-32768,-32768,-32768,-32768,-32768,   111,-32768,
   111,-32768,    23,-32768,-32768,    54,-32768,-32768,-32768,-32768,
-32768,    50,    47,    70,-32768,    55,    27,    20,-32768,    57,
-32768,-32768,-32768,    56,   276,   111,    69,-32768,-32768,    88,
   288,-32768,   111,    23,-32768,    59,   111,   216,    99,-32768,
-32768,    89,-32768,-32768,    87,   117,-32768,   111,   111,-32768,
-32768,-32768,-32768,-32768,-32768,   172,-32768,-32768,   172,-32768,
-32768,-32768,   172,   111,   111,   111,   111,   111,   111,-32768,
-32768,    96,-32768,    47,    97,   119,    98,-32768,-32768,   -33,
-32768,   -30,-32768,-32768,   111,   100,   101,   111,   111,-32768,
   117,   103,    70,-32768,    27,    20,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   124,   102,-32768,-32768,-32768,-32768,
-32768,   -27,-32768,   111,-32768,   105,-32768,   104,-32768,-32768,
   110,-32768,-32768,-32768,-32768,   141,   178,   178,-32768,   -29,
   112,-32768,-32768,   116,-32768,   145,-32768,   111,-32768,   111,
-32768,   150,   178,-32768,   115,   133,-32768,   151,   152,-32768,
-32768,-32768,   112,   150,-32768,-32768,-32768,-32768,   212,   213,
-32768
};

static const short yypgoto[] = {-32768,
   201,-32768,-32768,-32768,   113,     1,-32768,   -25,-32768,-32768,
-32768,-32768,   165,-32768,    30,-32768,-32768,-32768,-32768,-32768,
    32,-32768,-32768,-32768,    -5,-32768,     5,-32768,-32768,    -3,
    38,-32768,-32768,-32768,   108,-32768,-32768,-32768,-32768,-32768,
-32768,   -55,-32768,-32768,    62,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   -64,   -98,   106,   -76,
-32768,-32768,    94,-32768,   122,-32768,    93,   -77,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,    17,-32768,-32768
};


#define	YYLAST		303


static const short yytable[] = {    84,
    15,   124,   123,   116,    17,   128,    47,   154,   128,   128,
    20,   128,   107,    15,   160,   119,   125,    17,   162,    34,
    35,    41,    22,    38,    57,    43,    62,    32,   124,    55,
   190,   209,    24,   191,   219,   124,    25,    26,    48,   124,
    73,    74,    75,    76,    77,    78,   108,    58,    45,    35,
   124,   124,   174,   166,    51,    28,   105,    52,   124,    29,
    30,   124,    56,    42,    63,   124,   192,    44,    79,   140,
   141,   142,   111,   115,   137,   138,   113,    81,   114,   178,
   179,   180,   181,   182,   183,   128,   117,   124,    47,   144,
   145,   146,   147,   148,   149,   210,   130,   131,   132,   133,
   134,   135,   118,   195,   198,   105,   120,   121,   127,   129,
   126,   150,   151,   152,   167,    38,   124,   161,   164,    66,
     2,     3,     4,     5,     6,     7,     8,     9,    67,    68,
   155,    11,    69,    70,    71,    72,    73,    74,    75,    76,
    77,    78,    73,    74,    75,    76,    77,    78,   157,   169,
   170,   216,   217,   225,   184,   227,   187,   -31,   193,   189,
   200,   201,    58,   194,    79,   213,   -38,   230,   212,   215,
    79,   220,   222,    81,   -87,    80,   223,   228,   231,    81,
    66,     2,     3,     4,     5,     6,     7,     8,     9,    67,
    68,   232,    11,    69,    70,    71,    72,    73,    74,    75,
    76,    77,    78,    73,    74,    75,    76,    77,    78,   236,
   234,   240,   241,    33,    61,   205,   203,   153,   159,     2,
     3,     4,     5,     6,     7,     8,     9,    67,   238,   175,
    11,    79,   199,   173,    81,   177,    80,     0,     0,     0,
    81,    73,    74,    75,    76,    77,    78,    -3,     1,   237,
     0,     2,     3,     4,     5,     6,     7,     8,     9,    10,
   176,     0,    11,     0,     0,     0,     0,     0,     0,    79,
     0,     0,     0,     0,   163,     0,     0,     0,    81,     2,
     3,     4,     5,     6,     7,     8,     9,    67,     0,     0,
    11,     2,     3,     4,     5,     6,     7,     8,     9,     0,
     0,     0,    11
};

static const short yycheck[] = {    55,
     0,    79,    79,    68,     0,    39,    32,   106,    39,    39,
     4,    39,    28,    13,   113,    71,    81,    13,   117,    26,
    27,    25,     4,    19,    38,    29,    52,    26,   106,    64,
    64,    59,     4,    64,    64,   113,     8,     9,    63,   117,
    26,    27,    28,    29,    30,    31,    62,    61,    26,    27,
   128,   129,   129,   118,    59,     4,    56,    60,   136,     8,
     9,   139,    57,    26,    26,   143,   165,    30,    54,    50,
    51,    52,    60,    59,    48,    49,    63,    63,    26,   144,
   145,   146,   147,   148,   149,    39,    63,   165,   114,    33,
    34,    35,    36,    37,    38,   194,    42,    43,    44,    45,
    46,    47,    63,   168,   169,   105,    59,    63,    59,    40,
    57,    55,    56,    58,    16,   111,   194,    59,   118,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    62,    15,    16,    17,    18,    19,    26,    27,    28,    29,
    30,    31,    26,    27,    28,    29,    30,    31,    61,    61,
    64,   207,   208,   218,    59,   220,    38,    61,    59,    62,
    58,    38,    61,    63,    54,    62,    57,   223,    64,    29,
    54,    60,    57,    63,    58,    59,    32,    28,    64,    63,
     3,     4,     5,     6,     7,     8,     9,    10,    11,    12,
    13,    59,    15,    16,    17,    18,    19,    26,    27,    28,
    29,    30,    31,    26,    27,    28,    29,    30,    31,    58,
    60,     0,     0,    13,    50,   186,   185,   105,   111,     4,
     5,     6,     7,     8,     9,    10,    11,    12,   234,   136,
    15,    54,   171,   128,    63,   143,    59,    -1,    -1,    -1,
    63,    26,    27,    28,    29,    30,    31,     0,     1,   233,
    -1,     4,     5,     6,     7,     8,     9,    10,    11,    12,
   139,    -1,    15,    -1,    -1,    -1,    -1,    -1,    -1,    54,
    -1,    -1,    -1,    -1,    59,    -1,    -1,    -1,    63,     4,
     5,     6,     7,     8,     9,    10,    11,    12,    -1,    -1,
    15,     4,     5,     6,     7,     8,     9,    10,    11,    -1,
    -1,    -1,    15
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 8:
#line 107 "parser.y"
{ insert_type(); ;
    break;}
case 18:
#line 126 "parser.y"
{ if(check_function(current_identifier))
						  {yyerror("ERROR: Identifier cannot be same as function name!"); }
						  if(duplicate(current_identifier)){yyerror("Duplicate value!");}insert_SymbolTable_nest(current_identifier,current_nested_val); insert_type(); ;
    break;}
case 20:
#line 129 "parser.y"
{if(duplicate(current_identifier)){yyerror("Duplicate value!");}insert_SymbolTable_nest(current_identifier,current_nested_val); insert_type();  ;
    break;}
case 23:
#line 131 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 26:
#line 135 "parser.y"
{ insert_dimensions(); arr_dim = 0;;
    break;}
case 27:
#line 138 "parser.y"
{arr_dim++; insert_dimensions(); arr_dim = 0;;
    break;}
case 28:
#line 138 "parser.y"
{if(yyval < 1) {yyerror("Array must have size greater than 1!"); } ;
    break;}
case 29:
#line 139 "parser.y"
{ arr_dim = 1 ;insert_dimensions(); arr_dim = 0;;
    break;}
case 31:
#line 140 "parser.y"
{arr_dim++;;
    break;}
case 36:
#line 148 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 37:
#line 148 "parser.y"
{ insert_value(); ;
    break;}
case 38:
#line 151 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 65:
#line 185 "parser.y"
{strcpy(currfunctype, current_type); check_duplicate(current_identifier); insert_SymbolTable_function(current_identifier);  strcpy(current_function,current_identifier); insert_type();;
    break;}
case 67:
#line 191 "parser.y"
{ check_params(current_type); ;
    break;}
case 68:
#line 191 "parser.y"
{insert_SymbolTable_paramscount(current_function, params_count);;
    break;}
case 73:
#line 201 "parser.y"
{insert_parameters(); insert_type(); insert_SymbolTable_nest(current_identifier,1); params_count++;;
    break;}
case 84:
#line 214 "parser.y"
{current_nested_val++;;
    break;}
case 85:
#line 214 "parser.y"
{remove_scope(current_nested_val);current_nested_val--;;
    break;}
case 90:
#line 225 "parser.y"
{if(yyvsp[-1]!=1){yyerror("ERROR: Here, condition must have integer value!");};
    break;}
case 94:
#line 232 "parser.y"
{if(yyvsp[-1]!=1){yyerror("ERROR: Here, condition must have integer value!");};
    break;}
case 96:
#line 233 "parser.y"
{if(yyvsp[-1]!=1){yyerror("Here, condition must have integer value!");};
    break;}
case 98:
#line 234 "parser.y"
{if(yyvsp[-1]!=1){yyerror("ERROR: Here, condition must have integer value!");};
    break;}
case 103:
#line 242 "parser.y"
{if(strcmp(currfunctype,"void")) {yyerror("ERROR: Cannot have void return for non-void function!"); };
    break;}
case 104:
#line 243 "parser.y"
{ 	if(!strcmp(currfunctype, "void"))
										{
											yyerror("Non-void return for void function!"); ;
										}

										if((currfunctype[0]=='i' || currfunctype[0]=='c') && yyvsp[-1]!=1)
										{
											yyerror("Expression doesn't match return type of function");;
										}

			                     	;
    break;}
case 106:
#line 260 "parser.y"
{					strcpy(previous_operator,"=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
																	  {
			                                                          yyval=1;
			                                                          }
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch"); }
			                                                       ;
    break;}
case 107:
#line 268 "parser.y"
{					strcpy(previous_operator,"+=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch"); }
			                                                       ;
    break;}
case 108:
#line 274 "parser.y"
{					strcpy(previous_operator,"-=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch"); }
			                                                       ;
    break;}
case 109:
#line 281 "parser.y"
{					strcpy(previous_operator,"*=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch"); }
			                                                       ;
    break;}
case 110:
#line 287 "parser.y"
{				strcpy(previous_operator,"/=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch");}
			                                                       ;
    break;}
case 111:
#line 293 "parser.y"
{					strcpy(previous_operator,"%=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch"); }
			                                                       ;
    break;}
case 112:
#line 300 "parser.y"
{if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 113:
#line 301 "parser.y"
{if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 114:
#line 302 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 115:
#line 307 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 116:
#line 308 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 117:
#line 311 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 118:
#line 312 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 119:
#line 315 "parser.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 120:
#line 316 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 121:
#line 319 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 122:
#line 320 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 123:
#line 323 "parser.y"
{strcpy(previous_operator,">=");;
    break;}
case 124:
#line 324 "parser.y"
{strcpy(previous_operator,"<=");;
    break;}
case 125:
#line 325 "parser.y"
{strcpy(previous_operator,">");;
    break;}
case 126:
#line 326 "parser.y"
{strcpy(previous_operator,"<");;
    break;}
case 127:
#line 327 "parser.y"
{strcpy(previous_operator,"==");;
    break;}
case 128:
#line 328 "parser.y"
{strcpy(previous_operator,"!=");;
    break;}
case 129:
#line 331 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 130:
#line 332 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 133:
#line 339 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 134:
#line 340 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 138:
#line 346 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 139:
#line 347 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 140:
#line 350 "parser.y"
{
			              if(!check_scope(current_identifier))
			              {printf("%s\n",current_identifier);yyerror("Identifier undeclared");}
			              if(!check_array(current_identifier))
			              {printf("%s\n",current_identifier);yyerror("Array Identifier has No Subscript");}
			              if(gettype(current_identifier,0)=='i' || gettype(current_identifier,1)== 'c')
			              yyval = 1;
			              else
			              yyval = -1;
			              ;
    break;}
case 141:
#line 360 "parser.y"
{if(!check_scope(current_identifier)){printf("%s\n",current_identifier);yyerror("Identifier undeclared");};
    break;}
case 142:
#line 361 "parser.y"
{if(gettype(current_identifier,0)=='i' || gettype(current_identifier,1)== 'c')
			              		yyval = 1;
			              		else
			              		yyval = -1;
			              		;
    break;}
case 143:
#line 368 "parser.y"
{if(yyvsp[-1]==1) yyval=1; else yyval=-1;;
    break;}
case 145:
#line 370 "parser.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 146:
#line 373 "parser.y"
{ strcpy(previous_operator,"(");
			             if(!check_declaration(current_identifier, "Function"))
			             { yyerror("Function not declared"); }
			             insert_SymbolTable_function(current_identifier);
						 strcpy(currfunccall,current_identifier);
			             ;
    break;}
case 147:
#line 379 "parser.y"
{ if(strcmp(currfunccall,"printf"))
							{
								if(getSTparamscount(currfunccall)!=call_params_count)
								{
									yyerror("Number of parameters not same as number of arguments during function call!");
							
								}
							}
						 ;
    break;}
case 150:
#line 393 "parser.y"
{ call_params_count++; ;
    break;}
case 152:
#line 396 "parser.y"
{ call_params_count++; ;
    break;}
case 155:
#line 400 "parser.y"
{  insert_type(); yyval=1; ;
    break;}
case 156:
#line 401 "parser.y"
{  insert_type(); yyval=-1;;
    break;}
case 157:
#line 402 "parser.y"
{  insert_type(); ;
    break;}
case 158:
#line 403 "parser.y"
{  insert_type();yyval=1; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 406 "parser.y"


extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insert_SymbolTable_type(char *,char *);
void insert_SymbolTable_value(char *, char *);
void insert_ConstantTable(char *, char *);
void insert_SymbolTable_arraydim(char *, char *);
void insert_SymbolTable_funcparam(char *, char *);
void printSymbolTable();
void printConstantTable();


int main()
{
	yyin = fopen("test2.c", "r");
	init_error_table();
	yyparse();

		printf("%30s SYMBOL TABLE \n", " ");
		printf("%30s %s\n", " ", "------------");
		printSymbolTable();

		printf("\n\n%30s CONSTANT TABLE \n", " ");
		printf("%30s %s\n", " ", "--------------");
		printConstantTable();

		printf("\n\n%30s ERROR TABLE \n", " ");
		printf("%30s %s\n", " ", "--------------");		
		print_error_table();
}

void yyerror(char *s)
{
	insert_error_table(yylineno, s);
}

void insert_type()
{
	insert_SymbolTable_type(current_identifier,current_type);
}

void insert_value()
{
	if(strcmp(previous_operator, "=") == 0)
	{	insert_SymbolTable_value(current_identifier,current_value);
	}
}

void insert_dimensions()
{	
	int len = snprintf(NULL,0,"%d",arr_dim);
	char* result = malloc(len+1);
	snprintf(result,len+1,"%d",arr_dim);
    insert_SymbolTable_arraydim(current_identifier, result);
}


void insert_parameters()
{
    insert_SymbolTable_funcparam(current_function, current_identifier);
}

int yywrap()
{
	return 1;
}
