#define YY_PARSE_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

	void yyerror(char* s);
	int yylex();
	#include "stdio.h"
	#include "stdlib.h"
	#include "ctype.h"
	#include "string.h"
	void insert_type();
	void insert_value();
	void insert_dimensions();
	void insert_parameters();
	void remove_scope (int );
	int check_scope(char*);
	int check_function(char *);
	void insert_SymbolTable_nest(char*, int);
	void insert_SymbolTable_paramscount(char*, int);
	int getSTparamscount(char*);
	int check_duplicate(char*);
	int check_declaration(char*, char *);
	int check_params(char*);
	int duplicate(char *s);
	int check_array(char*);
	void insert_SymbolTable_function(char*);
	char gettype(char*,int);

	extern int flag;
	int insert_flag = 0;

	extern char current_identifier[20];
	extern char current_type[20];
	extern char current_value[20];
    extern char current_function[20];
	extern char previous_operator[20];
	extern int current_nested_val;
	char currfunctype[100];
	char currfunccall[100];
	extern int params_count;
	int call_params_count;


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_PARSE_BISON 1

#ifndef YY_PARSE_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_PARSE_COMPATIBILITY 1
 #else
  #define  YY_PARSE_COMPATIBILITY 0
 #endif
#endif

#if YY_PARSE_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_PARSE_LTYPE
   #define YY_PARSE_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_PARSE_STYPE 
   #define YY_PARSE_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_PARSE_DEBUG
   #define  YY_PARSE_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_PARSE_USE_GOTO
  #define YY_PARSE_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_PARSE_USE_GOTO
 #define YY_PARSE_USE_GOTO 0
#endif

#ifndef YY_PARSE_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_PARSE_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_PARSE_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_PARSE_DEBUG */
#endif


#ifndef YY_PARSE_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_PARSE_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_PARSE_LSP_NEEDED
#ifndef YY_PARSE_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_PARSE_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_PARSE_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_PARSE_STYPE
#define YY_PARSE_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_PARSE_PARSE
#define YY_PARSE_PARSE yyparse
#endif
#ifndef YY_PARSE_LEX
#define YY_PARSE_LEX yylex
#endif
#ifndef YY_PARSE_LVAL
#define YY_PARSE_LVAL yylval
#endif
#ifndef YY_PARSE_LLOC
#define YY_PARSE_LLOC yylloc
#endif
#ifndef YY_PARSE_CHAR
#define YY_PARSE_CHAR yychar
#endif
#ifndef YY_PARSE_NERRS
#define YY_PARSE_NERRS yynerrs
#endif
#ifndef YY_PARSE_DEBUG_FLAG
#define YY_PARSE_DEBUG_FLAG yydebug
#endif
#ifndef YY_PARSE_ERROR
#define YY_PARSE_ERROR yyerror
#endif

#ifndef YY_PARSE_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_PARSE_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_PARSE_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_PARSE_PARSE_PARAM
  #define YY_PARSE_PARSE_PARAM void
 #endif
#endif

#if YY_PARSE_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_PARSE_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_PARSE_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_PARSE_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_PARSE_PURE
#  ifndef YYPURE
#    define YYPURE YY_PARSE_PURE
#  endif
#endif

#ifdef YY_PARSE_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_PARSE_DEBUG 
#  endif
#endif

#ifndef YY_PARSE_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_PARSE_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_PARSE_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_PARSE_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	DOUBLE	262
#define	LONG	263
#define	SHORT	264
#define	SIGNED	265
#define	UNSIGNED	266
#define	STRUCT	267
#define	RETURN	268
#define	MAIN	269
#define	VOID	270
#define	WHILE	271
#define	FOR	272
#define	DO	273
#define	BREAK	274
#define	CONTINUE	275
#define	GOTO	276
#define	ENDIF	277
#define	SWITCH	278
#define	CASE	279
#define	DEFAULT	280
#define	identifier	281
#define	array_identifier	282
#define	integer_constant	283
#define	string_constant	284
#define	float_constant	285
#define	character_constant	286
#define	ELSE	287
#define	MOD_EQUAL	288
#define	MULTIPLY_EQUAL	289
#define	DIVIDE_EQUAL	290
#define	ADD_EQUAL	291
#define	SUBTRACT_EQUAL	292
#define	OR_OR	293
#define	AND_AND	294
#define	EQUAL	295
#define	NOT_EQUAL	296
#define	LESS_EQUAL	297
#define	LESS	298
#define	GREAT_EQUAL	299
#define	GREAT	300
#define	SIZEOF	301
#define	NOT	302
#define	INCREMENT	303
#define	DECREMENT	304


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_PARSE_CLASS
#define YY_PARSE_CLASS PARSE
#endif
#ifndef YY_PARSE_INHERIT
#define YY_PARSE_INHERIT
#endif
#ifndef YY_PARSE_MEMBERS
#define YY_PARSE_MEMBERS 
#endif
#ifndef YY_PARSE_LEX_BODY
#define YY_PARSE_LEX_BODY  
#endif
#ifndef YY_PARSE_ERROR_BODY
#define YY_PARSE_ERROR_BODY  
#endif
#ifndef YY_PARSE_CONSTRUCTOR_PARAM
#define YY_PARSE_CONSTRUCTOR_PARAM
#endif
#ifndef YY_PARSE_CONSTRUCTOR_CODE
#define YY_PARSE_CONSTRUCTOR_CODE
#endif
#ifndef YY_PARSE_CONSTRUCTOR_INIT
#define YY_PARSE_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_PARSE_USE_CONST_TOKEN
#define YY_PARSE_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_PARSE_USE_CONST_TOKEN != 0
#ifndef YY_PARSE_ENUM_TOKEN
#define YY_PARSE_ENUM_TOKEN yy_PARSE_enum_token
#endif
#endif

class YY_PARSE_CLASS YY_PARSE_INHERIT
{
public: 
#if YY_PARSE_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int LONG;
static const int SHORT;
static const int SIGNED;
static const int UNSIGNED;
static const int STRUCT;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int DO;
static const int BREAK;
static const int CONTINUE;
static const int GOTO;
static const int ENDIF;
static const int SWITCH;
static const int CASE;
static const int DEFAULT;
static const int identifier;
static const int array_identifier;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int MOD_EQUAL;
static const int MULTIPLY_EQUAL;
static const int DIVIDE_EQUAL;
static const int ADD_EQUAL;
static const int SUBTRACT_EQUAL;
static const int OR_OR;
static const int AND_AND;
static const int EQUAL;
static const int NOT_EQUAL;
static const int LESS_EQUAL;
static const int LESS;
static const int GREAT_EQUAL;
static const int GREAT;
static const int SIZEOF;
static const int NOT;
static const int INCREMENT;
static const int DECREMENT;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_PARSE_ENUM_TOKEN { YY_PARSE_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,DOUBLE=262
	,LONG=263
	,SHORT=264
	,SIGNED=265
	,UNSIGNED=266
	,STRUCT=267
	,RETURN=268
	,MAIN=269
	,VOID=270
	,WHILE=271
	,FOR=272
	,DO=273
	,BREAK=274
	,CONTINUE=275
	,GOTO=276
	,ENDIF=277
	,SWITCH=278
	,CASE=279
	,DEFAULT=280
	,identifier=281
	,array_identifier=282
	,integer_constant=283
	,string_constant=284
	,float_constant=285
	,character_constant=286
	,ELSE=287
	,MOD_EQUAL=288
	,MULTIPLY_EQUAL=289
	,DIVIDE_EQUAL=290
	,ADD_EQUAL=291
	,SUBTRACT_EQUAL=292
	,OR_OR=293
	,AND_AND=294
	,EQUAL=295
	,NOT_EQUAL=296
	,LESS_EQUAL=297
	,LESS=298
	,GREAT_EQUAL=299
	,GREAT=300
	,SIZEOF=301
	,NOT=302
	,INCREMENT=303
	,DECREMENT=304


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_PARSE_PARSE (YY_PARSE_PARSE_PARAM);
 virtual void YY_PARSE_ERROR(char *msg) YY_PARSE_ERROR_BODY;
#ifdef YY_PARSE_PURE
#ifdef YY_PARSE_LSP_NEEDED
 virtual int  YY_PARSE_LEX (YY_PARSE_STYPE *YY_PARSE_LVAL,YY_PARSE_LTYPE *YY_PARSE_LLOC) YY_PARSE_LEX_BODY;
#else
 virtual int  YY_PARSE_LEX (YY_PARSE_STYPE *YY_PARSE_LVAL) YY_PARSE_LEX_BODY;
#endif
#else
 virtual int YY_PARSE_LEX() YY_PARSE_LEX_BODY;
 YY_PARSE_STYPE YY_PARSE_LVAL;
#ifdef YY_PARSE_LSP_NEEDED
 YY_PARSE_LTYPE YY_PARSE_LLOC;
#endif
 int   YY_PARSE_NERRS;
 int    YY_PARSE_CHAR;
#endif
#if YY_PARSE_DEBUG != 0
 int YY_PARSE_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_PARSE_CLASS(YY_PARSE_CONSTRUCTOR_PARAM);
public:
 YY_PARSE_MEMBERS 
};
/* other declare folow */
#if YY_PARSE_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_PARSE_CLASS::IF=258;
const int YY_PARSE_CLASS::INT=259;
const int YY_PARSE_CLASS::CHAR=260;
const int YY_PARSE_CLASS::FLOAT=261;
const int YY_PARSE_CLASS::DOUBLE=262;
const int YY_PARSE_CLASS::LONG=263;
const int YY_PARSE_CLASS::SHORT=264;
const int YY_PARSE_CLASS::SIGNED=265;
const int YY_PARSE_CLASS::UNSIGNED=266;
const int YY_PARSE_CLASS::STRUCT=267;
const int YY_PARSE_CLASS::RETURN=268;
const int YY_PARSE_CLASS::MAIN=269;
const int YY_PARSE_CLASS::VOID=270;
const int YY_PARSE_CLASS::WHILE=271;
const int YY_PARSE_CLASS::FOR=272;
const int YY_PARSE_CLASS::DO=273;
const int YY_PARSE_CLASS::BREAK=274;
const int YY_PARSE_CLASS::CONTINUE=275;
const int YY_PARSE_CLASS::GOTO=276;
const int YY_PARSE_CLASS::ENDIF=277;
const int YY_PARSE_CLASS::SWITCH=278;
const int YY_PARSE_CLASS::CASE=279;
const int YY_PARSE_CLASS::DEFAULT=280;
const int YY_PARSE_CLASS::identifier=281;
const int YY_PARSE_CLASS::array_identifier=282;
const int YY_PARSE_CLASS::integer_constant=283;
const int YY_PARSE_CLASS::string_constant=284;
const int YY_PARSE_CLASS::float_constant=285;
const int YY_PARSE_CLASS::character_constant=286;
const int YY_PARSE_CLASS::ELSE=287;
const int YY_PARSE_CLASS::MOD_EQUAL=288;
const int YY_PARSE_CLASS::MULTIPLY_EQUAL=289;
const int YY_PARSE_CLASS::DIVIDE_EQUAL=290;
const int YY_PARSE_CLASS::ADD_EQUAL=291;
const int YY_PARSE_CLASS::SUBTRACT_EQUAL=292;
const int YY_PARSE_CLASS::OR_OR=293;
const int YY_PARSE_CLASS::AND_AND=294;
const int YY_PARSE_CLASS::EQUAL=295;
const int YY_PARSE_CLASS::NOT_EQUAL=296;
const int YY_PARSE_CLASS::LESS_EQUAL=297;
const int YY_PARSE_CLASS::LESS=298;
const int YY_PARSE_CLASS::GREAT_EQUAL=299;
const int YY_PARSE_CLASS::GREAT=300;
const int YY_PARSE_CLASS::SIZEOF=301;
const int YY_PARSE_CLASS::NOT=302;
const int YY_PARSE_CLASS::INCREMENT=303;
const int YY_PARSE_CLASS::DECREMENT=304;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_PARSE_CLASS::token */
#endif
/*apres const  */
YY_PARSE_CLASS::YY_PARSE_CLASS(YY_PARSE_CONSTRUCTOR_PARAM) YY_PARSE_CONSTRUCTOR_INIT
{
#if YY_PARSE_DEBUG != 0
YY_PARSE_DEBUG_FLAG=0;
#endif
YY_PARSE_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		237
#define	YYFLAG		-32768
#define	YYNTBASE	65

#define YYTRANSLATE(x) ((unsigned)(x) <= 304 ? yytranslate[x] : 142)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    52,     2,     2,    63,
    64,    50,    48,    60,    49,     2,    51,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    59,     2,
    38,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    61,     2,    62,    41,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    57,     2,    58,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    39,    40,    42,    43,    44,    45,    46,    47,
    53,    54,    55,    56
};

#if YY_PARSE_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     6,     8,    10,    12,    13,    21,    24,
    25,    29,    31,    35,    38,    41,    42,    43,    47,    48,
    52,    54,    55,    59,    62,    63,    64,    69,    72,    74,
    76,    77,    78,    82,    83,    89,    92,    95,    96,    98,
   100,   102,   104,   107,   110,   113,   116,   118,   120,   123,
   126,   127,   129,   132,   135,   136,   138,   139,   141,   142,
   145,   149,   153,   154,   158,   159,   162,   165,   166,   167,
   171,   174,   175,   177,   179,   181,   183,   185,   187,   189,
   190,   195,   198,   199,   202,   204,   205,   213,   216,   217,
   218,   225,   226,   235,   236,   245,   247,   250,   252,   255,
   259,   262,   266,   270,   274,   278,   282,   286,   289,   292,
   294,   298,   300,   304,   306,   309,   311,   315,   317,   319,
   321,   323,   325,   327,   329,   333,   335,   337,   339,   343,
   345,   347,   349,   351,   353,   355,   357,   358,   364,   368,
   370,   372,   373,   379,   381,   382,   383,   387,   388,   393,
   394,   396,   398,   400
};

static const short yyrhs[] = {    66,
     0,    67,    66,     0,     0,    71,     0,    95,     0,    68,
     0,     0,    12,    26,    69,    57,    70,    58,    59,     0,
    71,    70,     0,     0,    90,    73,    59,     0,    72,     0,
    12,    26,    73,     0,    75,    74,     0,    60,    73,     0,
     0,     0,    26,    76,    78,     0,     0,    27,    77,    78,
     0,    80,     0,     0,    38,    79,   121,     0,    61,    81,
     0,     0,     0,    28,    82,    62,    83,     0,    62,    84,
     0,    84,     0,    86,     0,     0,     0,    38,    85,    29,
     0,     0,    38,    87,    57,    88,    58,     0,    28,    89,
     0,    60,    88,     0,     0,     4,     0,     5,     0,     6,
     0,     7,     0,     8,    93,     0,     9,    94,     0,    11,
    91,     0,    10,    92,     0,    15,     0,     4,     0,     8,
    93,     0,     9,    94,     0,     0,     4,     0,     8,    93,
     0,     9,    94,     0,     0,     4,     0,     0,     4,     0,
     0,    96,    97,     0,    90,    26,    63,     0,    98,    64,
   105,     0,     0,    90,    99,   100,     0,     0,   102,   101,
     0,    60,    98,     0,     0,     0,    26,   103,   104,     0,
    61,    62,     0,     0,   109,     0,   106,     0,   110,     0,
   113,     0,   118,     0,   119,     0,    71,     0,     0,   107,
    57,   108,    58,     0,   105,   108,     0,     0,   120,    59,
     0,    59,     0,     0,     3,    63,   121,    64,   111,   105,
   112,     0,    32,   105,     0,     0,     0,    16,    63,   121,
    64,   114,   105,     0,     0,    17,    63,   117,   121,    59,
   115,   120,    64,     0,     0,    18,   105,    16,    63,   121,
    64,   116,    59,     0,    71,     0,   120,    59,     0,    59,
     0,    13,    59,     0,    13,   120,    59,     0,    19,    59,
     0,   131,    38,   120,     0,   131,    36,   120,     0,   131,
    37,   120,     0,   131,    34,   120,     0,   131,    35,   120,
     0,   131,    33,   120,     0,   131,    55,     0,   131,    56,
     0,   121,     0,   121,    39,   122,     0,   122,     0,   122,
    40,   123,     0,   123,     0,    54,   123,     0,   124,     0,
   124,   125,   126,     0,   126,     0,    46,     0,    44,     0,
    47,     0,    45,     0,    42,     0,    43,     0,   126,   127,
   128,     0,   128,     0,    48,     0,    49,     0,   128,   129,
   130,     0,   130,     0,    50,     0,    51,     0,    52,     0,
   133,     0,   131,     0,    26,     0,     0,    27,   132,    61,
   120,    62,     0,    63,   120,    64,     0,   134,     0,   141,
     0,     0,    26,    63,   135,   136,    64,     0,   137,     0,
     0,     0,   120,   138,   139,     0,     0,    60,   120,   140,
   139,     0,     0,    28,     0,    29,     0,    30,     0,    31,
     0
};

#endif

#if (YY_PARSE_DEBUG != 0) || defined(YY_PARSE_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    80,    83,    84,    88,    89,    90,    93,    93,    95,    95,
    98,    99,   102,   105,   108,   109,   112,   115,   115,   115,
   117,   117,   117,   120,   121,   124,   124,   125,   128,   129,
   130,   133,   133,   136,   136,   139,   142,   143,   147,   147,
   147,   147,   148,   149,   150,   151,   152,   155,   155,   155,
   155,   158,   158,   158,   158,   161,   161,   164,   164,   167,
   170,   173,   176,   176,   176,   179,   182,   183,   186,   186,
   189,   190,   193,   193,   194,   194,   195,   195,   196,   199,
   199,   202,   203,   206,   207,   210,   210,   213,   214,   217,
   218,   218,   218,   219,   219,   222,   223,   224,   227,   228,
   241,   245,   253,   259,   266,   272,   278,   285,   286,   287,
   291,   292,   295,   296,   299,   300,   303,   304,   307,   308,
   309,   310,   311,   312,   315,   316,   319,   320,   323,   324,
   327,   327,   327,   330,   331,   334,   344,   344,   352,   353,
   354,   357,   362,   375,   375,   378,   378,   381,   382,   382,
   385,   386,   387,   388
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","DOUBLE","LONG","SHORT","SIGNED","UNSIGNED","STRUCT","RETURN",
"MAIN","VOID","WHILE","FOR","DO","BREAK","CONTINUE","GOTO","ENDIF","SWITCH",
"CASE","DEFAULT","identifier","array_identifier","integer_constant","string_constant",
"float_constant","character_constant","ELSE","MOD_EQUAL","MULTIPLY_EQUAL","DIVIDE_EQUAL",
"ADD_EQUAL","SUBTRACT_EQUAL","'='","OR_OR","AND_AND","'^'","EQUAL","NOT_EQUAL",
"LESS_EQUAL","LESS","GREAT_EQUAL","GREAT","'+'","'-'","'*'","'/'","'%'","SIZEOF",
"NOT","INCREMENT","DECREMENT","'{'","'}'","';'","','","'['","']'","'('","')'",
"begin_parse","declarations","declaration","structure_dec","@1","structure_content",
"variable_dec","structure_initialize","variables","multiple_variables","identifier_name",
"@2","@3","extended_identifier","@4","array_iden","array_dims","@5","initilization",
"string_initilization","@6","array_initialization","@7","array_values","multiple_array_values",
"datatype","unsigned_grammar","signed_grammar","long_grammar","short_grammar",
"function_dec","function_datatype","function_parameters","parameters","@8","all_parameter_identifiers",
"multiple_parameters","parameter_identifier","@9","extended_parameter","statement",
"multiple_statement","@10","statments","expression_statment","conditional_statements",
"@11","extended_conditional_statements","iterative_statements","@12","@13","@14",
"for_initialization","return_statement","break_statement","expression","simple_expression",
"and_expression","unary_relation_expression","regular_expression","relational_operators",
"sum_expression","sum_operators","term","MULOP","factor","mutable","@15","immutable",
"call","@16","arguments","arguments_list","@17","A","@18","constant",""
};
#endif

static const short yyr1[] = {     0,
    65,    66,    66,    67,    67,    67,    69,    68,    70,    70,
    71,    71,    72,    73,    74,    74,    76,    75,    77,    75,
    78,    79,    78,    80,    80,    82,    81,    81,    83,    83,
    83,    85,    84,    87,    86,    88,    89,    89,    90,    90,
    90,    90,    90,    90,    90,    90,    90,    91,    91,    91,
    91,    92,    92,    92,    92,    93,    93,    94,    94,    95,
    96,    97,    99,    98,    98,   100,   101,   101,   103,   102,
   104,   104,   105,   105,   105,   105,   105,   105,   105,   107,
   106,   108,   108,   109,   109,   111,   110,   112,   112,   114,
   113,   115,   113,   116,   113,   117,   117,   117,   118,   118,
   119,   120,   120,   120,   120,   120,   120,   120,   120,   120,
   121,   121,   122,   122,   123,   123,   124,   124,   125,   125,
   125,   125,   125,   125,   126,   126,   127,   127,   128,   128,
   129,   129,   129,   130,   130,   131,   132,   131,   133,   133,
   133,   135,   134,   136,   136,   138,   137,   140,   139,   139,
   141,   141,   141,   141
};

static const short yyr2[] = {     0,
     1,     2,     0,     1,     1,     1,     0,     7,     2,     0,
     3,     1,     3,     2,     2,     0,     0,     3,     0,     3,
     1,     0,     3,     2,     0,     0,     4,     2,     1,     1,
     0,     0,     3,     0,     5,     2,     2,     0,     1,     1,
     1,     1,     2,     2,     2,     2,     1,     1,     2,     2,
     0,     1,     2,     2,     0,     1,     0,     1,     0,     2,
     3,     3,     0,     3,     0,     2,     2,     0,     0,     3,
     2,     0,     1,     1,     1,     1,     1,     1,     1,     0,
     4,     2,     0,     2,     1,     0,     7,     2,     0,     0,
     6,     0,     8,     0,     8,     1,     2,     1,     2,     3,
     2,     3,     3,     3,     3,     3,     3,     2,     2,     1,
     3,     1,     3,     1,     2,     1,     3,     1,     1,     1,
     1,     1,     1,     1,     3,     1,     1,     1,     3,     1,
     1,     1,     1,     1,     1,     1,     0,     5,     3,     1,
     1,     0,     5,     1,     0,     0,     3,     0,     4,     0,
     1,     1,     1,     1
};

static const short yydefact[] = {     3,
    39,    40,    41,    42,    57,    59,    55,    51,     0,    47,
     1,     3,     6,     4,    12,     0,     5,    65,    56,    43,
    58,    44,    52,    57,    59,    46,    48,    57,    59,    45,
     7,     2,    17,    19,     0,    16,    63,    60,     0,    53,
    54,    49,    50,    17,     0,    13,    61,    25,    25,    11,
     0,    14,     0,    80,    10,    22,     0,    18,    21,    20,
    15,    69,    64,    68,     0,     0,     0,     0,     0,    80,
     0,   136,   137,   151,   152,   153,   154,     0,    85,     0,
    79,     0,    62,    74,     0,    73,    75,    76,    77,    78,
     0,   110,   112,   114,   116,   118,   126,   130,   135,   134,
   140,   141,     0,    10,     0,    26,     0,    24,    72,    65,
    66,     0,     0,    99,     0,     0,     0,     0,   101,   142,
     0,   115,   135,     0,    80,    84,     0,     0,   123,   124,
   120,   122,   119,   121,     0,   127,   128,     0,   131,   132,
   133,     0,     0,     0,     0,     0,     0,     0,   108,   109,
     0,     9,    23,     0,    32,    28,     0,    70,    67,     0,
   100,     0,    98,    96,     0,     0,     0,   145,     0,   139,
    80,     0,   111,   113,   117,   125,   129,   107,   105,   106,
   103,   104,   102,     8,    31,     0,    71,    86,    90,     0,
    97,     0,   146,     0,   144,     0,    82,    81,    32,    27,
    29,    30,    33,    80,    80,    92,     0,   150,   143,   138,
     0,    89,    91,     0,    94,     0,   147,     0,    80,    87,
     0,     0,   148,    38,     0,    88,    93,    95,   150,     0,
    36,    35,   149,    37,     0,     0,     0
};

static const short yydefgoto[] = {   235,
    11,    12,    13,    45,   103,    81,    15,    35,    52,    36,
    48,    49,    58,   105,    59,   108,   154,   200,   156,   186,
   202,   211,   225,   231,    82,    30,    26,    20,    22,    17,
    18,    38,    39,    53,    63,   111,    64,   109,   158,   171,
    84,    85,   172,    86,    87,   204,   220,    88,   205,   214,
   222,   165,    89,    90,    91,    92,    93,    94,    95,   135,
    96,   138,    97,   142,    98,    99,   121,   100,   101,   168,
   194,   195,   208,   217,   229,   102
};

static const short yypact[] = {   243,
-32768,-32768,-32768,-32768,     7,    13,    66,    83,    -6,-32768,
-32768,   243,-32768,-32768,-32768,    12,-32768,   275,-32768,-32768,
-32768,-32768,-32768,     7,    13,-32768,-32768,     7,    13,-32768,
    50,-32768,   -38,-32768,    -9,     5,-32768,-32768,     9,-32768,
-32768,-32768,-32768,-32768,    14,-32768,-32768,    -1,    -1,-32768,
    50,-32768,    64,   177,   255,-32768,   -14,-32768,-32768,-32768,
-32768,-32768,-32768,    40,    38,    76,     4,    41,    45,   177,
    44,    46,-32768,-32768,-32768,-32768,-32768,    15,-32768,    15,
-32768,    50,-32768,-32768,    53,-32768,-32768,-32768,-32768,-32768,
    52,    73,    74,-32768,   155,    31,   -42,-32768,   103,-32768,
-32768,-32768,    57,   255,    15,-32768,    79,-32768,    87,   275,
-32768,    15,    50,-32768,    90,    15,   215,   137,-32768,-32768,
    94,-32768,-32768,    92,   116,-32768,    15,    15,-32768,-32768,
-32768,-32768,-32768,-32768,    67,-32768,-32768,    67,-32768,-32768,
-32768,    67,    15,    15,    15,    15,    15,    15,-32768,-32768,
    98,-32768,    73,    99,-32768,-32768,   100,-32768,-32768,   -17,
-32768,   -15,-32768,-32768,    15,   101,   104,    15,    15,-32768,
   116,   105,    74,-32768,    31,   -42,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   126,   139,-32768,-32768,-32768,   -32,
-32768,    15,-32768,   102,-32768,   107,-32768,-32768,   114,-32768,
-32768,-32768,-32768,   177,   177,-32768,   -11,   112,-32768,-32768,
   119,   141,-32768,    15,-32768,    15,-32768,   149,   177,-32768,
   127,   150,-32768,   118,   152,-32768,-32768,-32768,   112,   149,
-32768,-32768,-32768,-32768,   211,   212,-32768
};

static const short yypgoto[] = {-32768,
   201,-32768,-32768,-32768,   110,     1,-32768,   -25,-32768,-32768,
-32768,-32768,   166,-32768,-32768,-32768,-32768,-32768,    32,-32768,
-32768,-32768,   -12,-32768,     3,-32768,-32768,    33,    39,-32768,
-32768,-32768,   106,-32768,-32768,-32768,-32768,-32768,-32768,   -54,
-32768,-32768,    58,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   -62,   -93,   108,   -74,-32768,-32768,
    93,-32768,    95,-32768,    96,   -76,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,     8,-32768,-32768
};


#define	YYLAST		290


static const short yytable[] = {    83,
    14,   123,    16,   122,   115,    46,   127,   139,   140,   141,
    19,   153,    14,   106,    16,   118,    21,   124,   160,    31,
    37,   127,   162,   127,    47,    61,   206,   127,   123,    72,
    73,    74,    75,    76,    77,   123,    56,    33,    34,   123,
    72,    73,    74,    75,    76,    77,   188,   107,   189,    50,
   123,   123,   215,   174,   166,   104,    40,    78,   123,    57,
    42,   123,   114,    41,    51,   123,    80,    43,    78,    23,
    55,   190,    54,    24,    25,    44,    34,    80,   136,   137,
   178,   179,   180,   181,   182,   183,    27,    46,   123,    62,
    28,    29,    72,    73,    74,    75,    76,    77,   207,   110,
   112,   113,   119,   116,   104,   193,   196,   117,   120,   125,
   126,   127,    37,   128,   151,   123,   155,   164,    65,     1,
     2,     3,     4,     5,     6,     7,     8,    66,    67,    80,
    10,    68,    69,    70,    71,   143,   144,   145,   146,   147,
   148,    72,    73,    74,    75,    76,    77,   157,   161,   212,
   213,   221,   167,   223,   169,   170,   184,   149,   150,   191,
   185,   187,   198,   199,   226,   209,   192,   203,   210,    78,
   -34,   216,   219,   -83,    79,   218,   224,   230,    80,    65,
     1,     2,     3,     4,     5,     6,     7,     8,    66,    67,
   227,    10,    68,    69,    70,    71,   129,   130,   131,   132,
   133,   134,    72,    73,    74,    75,    76,    77,   228,   232,
   236,   237,    32,   152,    60,   159,   201,   234,     1,     2,
     3,     4,     5,     6,     7,     8,    66,   175,   197,    10,
    78,     0,   176,     0,   173,    79,   233,   177,     0,    80,
    72,    73,    74,    75,    76,    77,     1,     2,     3,     4,
     5,     6,     7,     8,     9,     0,     0,    10,     1,     2,
     3,     4,     5,     6,     7,     8,    66,     0,    78,    10,
     0,     0,     0,   163,     0,     0,     0,    80,     1,     2,
     3,     4,     5,     6,     7,     8,     0,     0,     0,    10
};

static const short yycheck[] = {    54,
     0,    78,     0,    78,    67,    31,    39,    50,    51,    52,
     4,   105,    12,    28,    12,    70,     4,    80,   112,    26,
    18,    39,   116,    39,    63,    51,    59,    39,   105,    26,
    27,    28,    29,    30,    31,   112,    38,    26,    27,   116,
    26,    27,    28,    29,    30,    31,    64,    62,    64,    59,
   127,   128,    64,   128,   117,    55,    24,    54,   135,    61,
    28,   138,    59,    25,    60,   142,    63,    29,    54,     4,
    57,   165,    64,     8,     9,    26,    27,    63,    48,    49,
   143,   144,   145,   146,   147,   148,     4,   113,   165,    26,
     8,     9,    26,    27,    28,    29,    30,    31,   192,    60,
    63,    26,    59,    63,   104,   168,   169,    63,    63,    57,
    59,    39,   110,    40,    58,   192,    38,   117,     3,     4,
     5,     6,     7,     8,     9,    10,    11,    12,    13,    63,
    15,    16,    17,    18,    19,    33,    34,    35,    36,    37,
    38,    26,    27,    28,    29,    30,    31,    61,    59,   204,
   205,   214,    16,   216,    61,    64,    59,    55,    56,    59,
    62,    62,    58,    38,   219,    64,    63,    29,    62,    54,
    57,    60,    32,    58,    59,    57,    28,    60,    63,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    64,    15,    16,    17,    18,    19,    42,    43,    44,    45,
    46,    47,    26,    27,    28,    29,    30,    31,    59,    58,
     0,     0,    12,   104,    49,   110,   185,   230,     4,     5,
     6,     7,     8,     9,    10,    11,    12,   135,   171,    15,
    54,    -1,   138,    -1,   127,    59,   229,   142,    -1,    63,
    26,    27,    28,    29,    30,    31,     4,     5,     6,     7,
     8,     9,    10,    11,    12,    -1,    -1,    15,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    -1,    54,    15,
    -1,    -1,    -1,    59,    -1,    -1,    -1,    63,     4,     5,
     6,     7,     8,     9,    10,    11,    -1,    -1,    -1,    15
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_PARSE_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_PARSE_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_PARSE_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_PARSE_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_PARSE_CHAR = (token), YY_PARSE_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_PARSE_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_PARSE_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_PARSE_PURE
/* UNPURE */
#define YYLEX           YY_PARSE_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_PARSE_CHAR;                      /*  the lookahead symbol        */
YY_PARSE_STYPE      YY_PARSE_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_PARSE_NERRS;                 /*  number of parse errors so far */
#ifdef YY_PARSE_LSP_NEEDED
YY_PARSE_LTYPE YY_PARSE_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_PARSE_LSP_NEEDED
#define YYLEX           YY_PARSE_LEX(&YY_PARSE_LVAL, &YY_PARSE_LLOC)
#else
#define YYLEX           YY_PARSE_LEX(&YY_PARSE_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_PARSE_DEBUG != 0
int YY_PARSE_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_PARSE_CLASS::
#endif
     YY_PARSE_PARSE(YY_PARSE_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_PARSE_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_PARSE_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_PARSE_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_PARSE_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_PARSE_LSP_NEEDED
  YY_PARSE_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_PARSE_LTYPE *yyls = yylsa;
  YY_PARSE_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_PARSE_PURE
  int YY_PARSE_CHAR;
  YY_PARSE_STYPE YY_PARSE_LVAL;
  int YY_PARSE_NERRS;
#ifdef YY_PARSE_LSP_NEEDED
  YY_PARSE_LTYPE YY_PARSE_LLOC;
#endif
#endif

  YY_PARSE_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_PARSE_DEBUG != 0
  if (YY_PARSE_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_PARSE_NERRS = 0;
  YY_PARSE_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_PARSE_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_PARSE_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_PARSE_LSP_NEEDED
      YY_PARSE_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_PARSE_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_PARSE_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_PARSE_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_PARSE_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_PARSE_LSP_NEEDED
      yyls = (YY_PARSE_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_PARSE_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_PARSE_DEBUG != 0
      if (YY_PARSE_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_PARSE_DEBUG != 0
  if (YY_PARSE_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_PARSE_CHAR == YYEMPTY)
    {
#if YY_PARSE_DEBUG != 0
      if (YY_PARSE_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_PARSE_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_PARSE_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_PARSE_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_PARSE_DEBUG != 0
      if (YY_PARSE_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_PARSE_CHAR);

#if YY_PARSE_DEBUG != 0
      if (YY_PARSE_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_PARSE_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_PARSE_CHAR, YY_PARSE_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_PARSE_DEBUG != 0
  if (YY_PARSE_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_PARSE_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_PARSE_CHAR != YYEOF)
    YY_PARSE_CHAR = YYEMPTY;

  *++yyvsp = YY_PARSE_LVAL;
#ifdef YY_PARSE_LSP_NEEDED
  *++yylsp = YY_PARSE_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_PARSE_DEBUG != 0
  if (YY_PARSE_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 7:
#line 93 "parser.y"
{ insert_type(); ;
    break;}
case 17:
#line 112 "parser.y"
{ if(check_function(current_identifier))
						  {yyerror("ERROR: Identifier cannot be same as function name!\n"); exit(8);}
						  if(duplicate(current_identifier)){yyerror("Duplicate value!\n");exit(0);}insert_SymbolTable_nest(current_identifier,current_nested_val); insert_type(); ;
    break;}
case 19:
#line 115 "parser.y"
{if(duplicate(current_identifier)){yyerror("Duplicate value!\n");exit(0);}insert_SymbolTable_nest(current_identifier,current_nested_val); insert_type();  ;
    break;}
case 22:
#line 117 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 26:
#line 124 "parser.y"
{insert_dimensions();;
    break;}
case 27:
#line 124 "parser.y"
{if(yyval < 1) {yyerror("Array must have size greater than 1!\n"); exit(0);} ;
    break;}
case 32:
#line 133 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 33:
#line 133 "parser.y"
{ insert_value(); ;
    break;}
case 34:
#line 136 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 61:
#line 170 "parser.y"
{strcpy(currfunctype, current_type); check_duplicate(current_identifier); insert_SymbolTable_function(current_identifier);  strcpy(current_function,current_identifier); insert_type();;
    break;}
case 63:
#line 176 "parser.y"
{ check_params(current_type); ;
    break;}
case 64:
#line 176 "parser.y"
{insert_SymbolTable_paramscount(current_function, params_count);;
    break;}
case 69:
#line 186 "parser.y"
{insert_parameters(); insert_type(); insert_SymbolTable_nest(current_identifier,1); params_count++;;
    break;}
case 80:
#line 199 "parser.y"
{current_nested_val++;;
    break;}
case 81:
#line 199 "parser.y"
{remove_scope(current_nested_val);current_nested_val--;;
    break;}
case 86:
#line 210 "parser.y"
{if(yyvsp[-1]!=1){yyerror("ERROR: Here, condition must have integer value!\n");exit(0);};
    break;}
case 90:
#line 217 "parser.y"
{if(yyvsp[-1]!=1){yyerror("ERROR: Here, condition must have integer value!\n");exit(0);};
    break;}
case 92:
#line 218 "parser.y"
{if(yyvsp[-1]!=1){yyerror("Here, condition must have integer value!\n");exit(0);};
    break;}
case 94:
#line 219 "parser.y"
{if(yyvsp[-1]!=1){yyerror("ERROR: Here, condition must have integer value!\n");exit(0);};
    break;}
case 99:
#line 227 "parser.y"
{if(strcmp(currfunctype,"void")) {yyerror("ERROR: Cannot have void return for non-void function!\n"); exit(0);};
    break;}
case 100:
#line 228 "parser.y"
{ 	if(!strcmp(currfunctype, "void"))
										{
											yyerror("Non-void return for void function!"); exit(0);
										}

										if((currfunctype[0]=='i' || currfunctype[0]=='c') && yyvsp[-1]!=1)
										{
											yyerror("Expression doesn't match return type of function\n"); exit(0);
										}

			                     	;
    break;}
case 102:
#line 245 "parser.y"
{					strcpy(previous_operator,"=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
																	  {
			                                                          yyval=1;
			                                                          }
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch\n"); exit(0);}
			                                                       ;
    break;}
case 103:
#line 253 "parser.y"
{					strcpy(previous_operator,"+=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch\n"); exit(0);}
			                                                       ;
    break;}
case 104:
#line 259 "parser.y"
{					strcpy(previous_operator,"-=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch\n"); exit(0);}
			                                                       ;
    break;}
case 105:
#line 266 "parser.y"
{					strcpy(previous_operator,"*=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch\n"); exit(0);}
			                                                       ;
    break;}
case 106:
#line 272 "parser.y"
{				strcpy(previous_operator,"/=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch\n"); exit(0);}
			                                                       ;
    break;}
case 107:
#line 278 "parser.y"
{					strcpy(previous_operator,"%=");
																	  if(yyvsp[-2]==1 && yyvsp[0]==1)
			                                                          yyval=1;
			                                                          else
			                                                          {yyval=-1; yyerror("Type Mismatch\n"); exit(0);}
			                                                       ;
    break;}
case 108:
#line 285 "parser.y"
{if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 109:
#line 286 "parser.y"
{if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 110:
#line 287 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 111:
#line 291 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 112:
#line 292 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 113:
#line 295 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 114:
#line 296 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 115:
#line 299 "parser.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 116:
#line 300 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 117:
#line 303 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 118:
#line 304 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 119:
#line 307 "parser.y"
{strcpy(previous_operator,">=");;
    break;}
case 120:
#line 308 "parser.y"
{strcpy(previous_operator,"<=");;
    break;}
case 121:
#line 309 "parser.y"
{strcpy(previous_operator,">");;
    break;}
case 122:
#line 310 "parser.y"
{strcpy(previous_operator,"<");;
    break;}
case 123:
#line 311 "parser.y"
{strcpy(previous_operator,"==");;
    break;}
case 124:
#line 312 "parser.y"
{strcpy(previous_operator,"!=");;
    break;}
case 125:
#line 315 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 126:
#line 316 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 129:
#line 323 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 130:
#line 324 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 134:
#line 330 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 135:
#line 331 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 136:
#line 334 "parser.y"
{
			              if(!check_scope(current_identifier))
			              {printf("%s\n",current_identifier);yyerror("Identifier undeclared\n");exit(0);}
			              if(!check_array(current_identifier))
			              {printf("%s\n",current_identifier);yyerror("Array Identifier has No Subscript\n");exit(0);}
			              if(gettype(current_identifier,0)=='i' || gettype(current_identifier,1)== 'c')
			              yyval = 1;
			              else
			              yyval = -1;
			              ;
    break;}
case 137:
#line 344 "parser.y"
{if(!check_scope(current_identifier)){printf("%s\n",current_identifier);yyerror("Identifier undeclared\n");exit(0);};
    break;}
case 138:
#line 345 "parser.y"
{if(gettype(current_identifier,0)=='i' || gettype(current_identifier,1)== 'c')
			              		yyval = 1;
			              		else
			              		yyval = -1;
			              		;
    break;}
case 139:
#line 352 "parser.y"
{if(yyvsp[-1]==1) yyval=1; else yyval=-1;;
    break;}
case 141:
#line 354 "parser.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 142:
#line 357 "parser.y"
{ strcpy(previous_operator,"(");
			             if(!check_declaration(current_identifier, "Function"))
			             { yyerror("Function not declared"); exit(0);}
			             insert_SymbolTable_function(current_identifier);
						 strcpy(currfunccall,current_identifier);
			             ;
    break;}
case 143:
#line 363 "parser.y"
{ if(strcmp(currfunccall,"printf"))
							{
								if(getSTparamscount(currfunccall)!=call_params_count)
								{
									yyerror("Number of parameters not same as number of arguments during function call!");
									//printf("Number of arguments in function call %s doesn't match number of parameters\n", currfunccall);
									exit(8);
								}
							}
						 ;
    break;}
case 146:
#line 378 "parser.y"
{ call_params_count++; ;
    break;}
case 148:
#line 381 "parser.y"
{ call_params_count++; ;
    break;}
case 151:
#line 385 "parser.y"
{  insert_type(); yyval=1; ;
    break;}
case 152:
#line 386 "parser.y"
{  insert_type(); yyval=-1;;
    break;}
case 153:
#line 387 "parser.y"
{  insert_type(); ;
    break;}
case 154:
#line 388 "parser.y"
{  insert_type();yyval=1; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_PARSE_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_PARSE_DEBUG != 0
  if (YY_PARSE_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_PARSE_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_PARSE_LLOC.first_line;
      yylsp->first_column = YY_PARSE_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_PARSE_NERRS;

#ifdef YY_PARSE_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_PARSE_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_PARSE_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_PARSE_ERROR_VERBOSE */
	YY_PARSE_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_PARSE_CHAR == YYEOF)
	YYABORT;

#if YY_PARSE_DEBUG != 0
      if (YY_PARSE_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_PARSE_CHAR, yytname[yychar1]);
#endif

      YY_PARSE_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_PARSE_LSP_NEEDED
  yylsp--;
#endif

#if YY_PARSE_DEBUG != 0
  if (YY_PARSE_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_PARSE_DEBUG != 0
  if (YY_PARSE_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_PARSE_LVAL;
#ifdef YY_PARSE_LSP_NEEDED
  *++yylsp = YY_PARSE_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 391 "parser.y"


extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insert_SymbolTable_type(char *,char *);
void insert_SymbolTable_value(char *, char *);
void insert_ConstantTable(char *, char *);
void insert_SymbolTable_arraydim(char *, char *);
void insert_SymbolTable_funcparam(char *, char *);
void printSymbolTable();
void printConstantTable();


int main()
{
	yyin = fopen("test2.c", "r");
	yyparse();

	if(flag == 0)
	{
		printf("VALID PARSE\n");
		printf("%30s SYMBOL TABLE \n", " ");
		printf("%30s %s\n", " ", "------------");
		printSymbolTable();

		printf("\n\n%30s CONSTANT TABLE \n", " ");
		printf("%30s %s\n", " ", "--------------");
		printConstantTable();
	}
}

void yyerror(char *s)
{
	printf("Line No. : %d %s %s\n",yylineno, s, yytext);
	flag=1;
	printf("\nUNSUCCESSFUL: INVALID PARSE\n");
}

void insert_type()
{
	insert_SymbolTable_type(current_identifier,current_type);
}

void insert_value()
{
	if(strcmp(previous_operator, "=") == 0)
	{	insert_SymbolTable_value(current_identifier,current_value);
	}
}

void insert_dimensions()
{
    insert_SymbolTable_arraydim(current_identifier, current_value);
}

void insert_parameters()
{
    insert_SymbolTable_funcparam(current_function, current_identifier);
}

int yywrap()
{
	return 1;
}
