#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

	void yyerror(char* s);
	int yylex();
	#include "stdio.h"
	#include "stdlib.h"
	#include "ctype.h"
	#include "string.h"
	void insert_type();
	void insert_value();
	void insert_dimensions();
	void insert_params();
	int insert_flag = 0;

	extern char current_id[20];
	extern char current_type[20];
	extern char current_value[20];
    extern char current_function[20];
	extern char previous_operator[20];


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	DOUBLE	262
#define	LONG	263
#define	SHORT	264
#define	SIGNED	265
#define	UNSIGNED	266
#define	STRUCT	267
#define	UNION	268
#define	RETURN	269
#define	MAIN	270
#define	VOID	271
#define	WHILE	272
#define	FOR	273
#define	DO	274
#define	BREAK	275
#define	CONTINUE	276
#define	GOTO	277
#define	ENDIF	278
#define	SWITCH	279
#define	CASE	280
#define	DEFAULT	281
#define	id	282
#define	integer_constant	283
#define	string_constant	284
#define	float_constant	285
#define	character_constant	286
#define	ELSE	287
#define	MOD_EQUAL	288
#define	MULTIPLY_EQUAL	289
#define	DIVIDE_EQUAL	290
#define	ADD_EQUAL	291
#define	SUBTRACT_EQUAL	292
#define	OR_OR	293
#define	AND_AND	294
#define	EQUAL	295
#define	NOT_EQUAL	296
#define	LESS_EQUAL	297
#define	LESS	298
#define	GREAT_EQUAL	299
#define	GREAT	300
#define	SIZEOF	301
#define	NOT	302
#define	INCREMENT	303
#define	DECREMENT	304


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int LONG;
static const int SHORT;
static const int SIGNED;
static const int UNSIGNED;
static const int STRUCT;
static const int UNION;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int DO;
static const int BREAK;
static const int CONTINUE;
static const int GOTO;
static const int ENDIF;
static const int SWITCH;
static const int CASE;
static const int DEFAULT;
static const int id;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int MOD_EQUAL;
static const int MULTIPLY_EQUAL;
static const int DIVIDE_EQUAL;
static const int ADD_EQUAL;
static const int SUBTRACT_EQUAL;
static const int OR_OR;
static const int AND_AND;
static const int EQUAL;
static const int NOT_EQUAL;
static const int LESS_EQUAL;
static const int LESS;
static const int GREAT_EQUAL;
static const int GREAT;
static const int SIZEOF;
static const int NOT;
static const int INCREMENT;
static const int DECREMENT;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,DOUBLE=262
	,LONG=263
	,SHORT=264
	,SIGNED=265
	,UNSIGNED=266
	,STRUCT=267
	,UNION=268
	,RETURN=269
	,MAIN=270
	,VOID=271
	,WHILE=272
	,FOR=273
	,DO=274
	,BREAK=275
	,CONTINUE=276
	,GOTO=277
	,ENDIF=278
	,SWITCH=279
	,CASE=280
	,DEFAULT=281
	,id=282
	,integer_constant=283
	,string_constant=284
	,float_constant=285
	,character_constant=286
	,ELSE=287
	,MOD_EQUAL=288
	,MULTIPLY_EQUAL=289
	,DIVIDE_EQUAL=290
	,ADD_EQUAL=291
	,SUBTRACT_EQUAL=292
	,OR_OR=293
	,AND_AND=294
	,EQUAL=295
	,NOT_EQUAL=296
	,LESS_EQUAL=297
	,LESS=298
	,GREAT_EQUAL=299
	,GREAT=300
	,SIZEOF=301
	,NOT=302
	,INCREMENT=303
	,DECREMENT=304


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::DOUBLE=262;
const int YY_parse_CLASS::LONG=263;
const int YY_parse_CLASS::SHORT=264;
const int YY_parse_CLASS::SIGNED=265;
const int YY_parse_CLASS::UNSIGNED=266;
const int YY_parse_CLASS::STRUCT=267;
const int YY_parse_CLASS::UNION=268;
const int YY_parse_CLASS::RETURN=269;
const int YY_parse_CLASS::MAIN=270;
const int YY_parse_CLASS::VOID=271;
const int YY_parse_CLASS::WHILE=272;
const int YY_parse_CLASS::FOR=273;
const int YY_parse_CLASS::DO=274;
const int YY_parse_CLASS::BREAK=275;
const int YY_parse_CLASS::CONTINUE=276;
const int YY_parse_CLASS::GOTO=277;
const int YY_parse_CLASS::ENDIF=278;
const int YY_parse_CLASS::SWITCH=279;
const int YY_parse_CLASS::CASE=280;
const int YY_parse_CLASS::DEFAULT=281;
const int YY_parse_CLASS::id=282;
const int YY_parse_CLASS::integer_constant=283;
const int YY_parse_CLASS::string_constant=284;
const int YY_parse_CLASS::float_constant=285;
const int YY_parse_CLASS::character_constant=286;
const int YY_parse_CLASS::ELSE=287;
const int YY_parse_CLASS::MOD_EQUAL=288;
const int YY_parse_CLASS::MULTIPLY_EQUAL=289;
const int YY_parse_CLASS::DIVIDE_EQUAL=290;
const int YY_parse_CLASS::ADD_EQUAL=291;
const int YY_parse_CLASS::SUBTRACT_EQUAL=292;
const int YY_parse_CLASS::OR_OR=293;
const int YY_parse_CLASS::AND_AND=294;
const int YY_parse_CLASS::EQUAL=295;
const int YY_parse_CLASS::NOT_EQUAL=296;
const int YY_parse_CLASS::LESS_EQUAL=297;
const int YY_parse_CLASS::LESS=298;
const int YY_parse_CLASS::GREAT_EQUAL=299;
const int YY_parse_CLASS::GREAT=300;
const int YY_parse_CLASS::SIZEOF=301;
const int YY_parse_CLASS::NOT=302;
const int YY_parse_CLASS::INCREMENT=303;
const int YY_parse_CLASS::DECREMENT=304;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		255
#define	YYFLAG		-32768
#define	YYNTBASE	66

#define YYTRANSLATE(x) ((unsigned)(x) <= 304 ? yytranslate[x] : 150)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    52,     2,     2,    63,
    64,    50,    48,    60,    49,    65,    51,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    59,     2,
    38,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    61,     2,    62,    41,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    57,     2,    58,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    39,    40,    42,    43,    44,    45,    46,    47,
    53,    54,    55,    56
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     6,     8,    10,    12,    14,    15,    23,
    26,    27,    28,    36,    39,    40,    44,    46,    48,    52,
    56,    59,    62,    63,    64,    68,    70,    71,    75,    78,
    79,    80,    85,    88,    90,    92,    93,    94,    98,    99,
   105,   108,   111,   112,   114,   116,   118,   120,   123,   126,
   129,   132,   134,   136,   139,   142,   143,   145,   148,   151,
   152,   154,   155,   157,   158,   161,   165,   169,   172,   173,
   176,   179,   180,   181,   185,   188,   189,   191,   193,   195,
   197,   199,   201,   203,   207,   210,   211,   214,   216,   223,
   226,   227,   233,   241,   249,   251,   254,   256,   259,   261,
   264,   267,   270,   272,   273,   277,   278,   282,   283,   287,
   288,   292,   293,   297,   298,   302,   304,   306,   309,   313,
   314,   317,   321,   322,   325,   327,   330,   333,   334,   336,
   338,   340,   342,   344,   346,   350,   352,   354,   356,   360,
   362,   364,   366,   368,   370,   372,   374,   377,   381,   384,
   385,   390,   392,   394,   395,   401,   403,   404,   407,   411,
   412,   414,   416,   418
};

static const short yyrhs[] = {    67,
     0,    68,    67,     0,     0,    75,     0,    99,     0,    69,
     0,    72,     0,     0,    12,    27,    70,    57,    71,    58,
    59,     0,    75,    71,     0,     0,     0,    13,    27,    73,
    57,    74,    58,    59,     0,    75,    74,     0,     0,    94,
    78,    59,     0,    76,     0,    77,     0,    12,    27,    78,
     0,    13,    27,    78,     0,    80,    79,     0,    78,    60,
     0,     0,     0,    27,    81,    82,     0,    84,     0,     0,
    38,    83,   119,     0,    61,    85,     0,     0,     0,    28,
    86,    62,    87,     0,    62,    88,     0,    88,     0,    90,
     0,     0,     0,    38,    89,    29,     0,     0,    38,    91,
    57,    92,    58,     0,    28,    93,     0,    60,    92,     0,
     0,     4,     0,     5,     0,     6,     0,     7,     0,     8,
    97,     0,     9,    98,     0,    11,    95,     0,    10,    96,
     0,    16,     0,     4,     0,     8,    97,     0,     9,    98,
     0,     0,     4,     0,     8,    97,     0,     9,    98,     0,
     0,     4,     0,     0,     4,     0,     0,   100,   101,     0,
    94,    27,    63,     0,   102,    64,   108,     0,    94,   103,
     0,     0,   105,   104,     0,    60,   102,     0,     0,     0,
    27,   106,   107,     0,    61,    62,     0,     0,   111,     0,
   109,     0,   112,     0,   114,     0,   116,     0,   118,     0,
    75,     0,    57,   110,    58,     0,   108,   110,     0,     0,
   119,    59,     0,    59,     0,     3,    63,   127,    64,   108,
   113,     0,    32,   108,     0,     0,    17,    63,   127,    64,
   108,     0,    18,    63,   115,   127,    59,   119,    64,     0,
    19,   108,    17,    63,   127,    64,    59,     0,    75,     0,
   119,    59,     0,    59,     0,    14,   117,     0,    59,     0,
   119,    59,     0,    20,    59,     0,   140,   120,     0,   127,
     0,     0,    38,   121,   119,     0,     0,    36,   122,   119,
     0,     0,    37,   123,   119,     0,     0,    34,   124,   119,
     0,     0,    35,   125,   119,     0,     0,    33,   126,   119,
     0,    55,     0,    56,     0,   129,   128,     0,    39,   129,
   128,     0,     0,   131,   130,     0,    40,   131,   130,     0,
     0,    54,   131,     0,   132,     0,   135,   133,     0,   134,
   135,     0,     0,    46,     0,    44,     0,    47,     0,    45,
     0,    42,     0,    43,     0,   135,   136,   137,     0,   137,
     0,    48,     0,    49,     0,   137,   138,   139,     0,   139,
     0,    50,     0,    51,     0,    52,     0,   142,     0,   140,
     0,    27,     0,   140,   141,     0,    61,   119,    62,     0,
    65,    27,     0,     0,    63,   143,   119,    64,     0,   144,
     0,   149,     0,     0,    27,    63,   145,   146,    64,     0,
   147,     0,     0,   119,   148,     0,    60,   119,   148,     0,
     0,    28,     0,    29,     0,    30,     0,    31,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    61,    64,    65,    69,    70,    71,    72,    75,    75,    77,
    77,    80,    80,    82,    82,    85,    86,    87,    91,    94,
    97,   100,   101,   104,   104,   106,   106,   106,   109,   110,
   113,   113,   114,   117,   118,   119,   122,   122,   125,   125,
   128,   131,   132,   136,   136,   136,   136,   137,   138,   139,
   140,   141,   144,   144,   144,   144,   147,   147,   147,   147,
   150,   150,   153,   153,   156,   159,   162,   165,   165,   168,
   171,   172,   175,   175,   178,   179,   182,   182,   183,   183,
   184,   184,   185,   188,   191,   192,   195,   196,   199,   202,
   203,   206,   207,   208,   211,   212,   213,   216,   219,   220,
   223,   226,   227,   230,   231,   231,   232,   232,   233,   233,
   234,   234,   235,   235,   236,   236,   237,   240,   243,   243,
   246,   249,   250,   253,   254,   257,   260,   261,   264,   265,
   266,   267,   268,   269,   272,   273,   276,   277,   280,   281,
   284,   284,   284,   287,   287,   290,   291,   294,   295,   298,
   298,   299,   299,   302,   302,   305,   305,   308,   311,   312,
   315,   316,   317,   318
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","DOUBLE","LONG","SHORT","SIGNED","UNSIGNED","STRUCT","UNION",
"RETURN","MAIN","VOID","WHILE","FOR","DO","BREAK","CONTINUE","GOTO","ENDIF",
"SWITCH","CASE","DEFAULT","id","integer_constant","string_constant","float_constant",
"character_constant","ELSE","MOD_EQUAL","MULTIPLY_EQUAL","DIVIDE_EQUAL","ADD_EQUAL",
"SUBTRACT_EQUAL","'='","OR_OR","AND_AND","'^'","EQUAL","NOT_EQUAL","LESS_EQUAL",
"LESS","GREAT_EQUAL","GREAT","'+'","'-'","'*'","'/'","'%'","SIZEOF","NOT","INCREMENT",
"DECREMENT","'{'","'}'","';'","','","'['","']'","'('","')'","'.'","program",
"declarations","declaration","struct_dec","@1","struct_content","union_dec",
"@2","union_content","var_dec","struct_init","union_init","vars","multiple_vars",
"id_name","@3","extended_id","@4","array_id","array_dims","@5","init","string_init",
"@6","array_init","@7","array_values","multiple_array_values","dtype","unsigned_grammar",
"signed_grammar","long_grammar","short_grammar","function_dec","function_dtype",
"function_params","params","all_parameter_ids","multiple_params","parameter_id",
"@8","extended_parameter","statement","multiple_statement","statements","expression_statement",
"conditional_statements","extended_conditional_statements","loop_statements",
"for_init","return_statement","return_suffix","break_statement","expression",
"expressions","@9","@10","@11","@12","@13","@14","simple_expression","simple_expression_breakup",
"and_expression","and_expression_breakup","unary_relation_expression","regex",
"regex_breakup","relops","sum_expression","sum_operators","term","multiply_operators",
"factor","identifier","extended_identifier","function","@15","function_call",
"@16","args","args_list","extended_args","constant",""
};
#endif

static const short yyr1[] = {     0,
    66,    67,    67,    68,    68,    68,    68,    70,    69,    71,
    71,    73,    72,    74,    74,    75,    75,    75,    76,    77,
    78,    79,    79,    81,    80,    82,    83,    82,    84,    84,
    86,    85,    85,    87,    87,    87,    89,    88,    91,    90,
    92,    93,    93,    94,    94,    94,    94,    94,    94,    94,
    94,    94,    95,    95,    95,    95,    96,    96,    96,    96,
    97,    97,    98,    98,    99,   100,   101,   102,   102,   103,
   104,   104,   106,   105,   107,   107,   108,   108,   108,   108,
   108,   108,   108,   109,   110,   110,   111,   111,   112,   113,
   113,   114,   114,   114,   115,   115,   115,   116,   117,   117,
   118,   119,   119,   121,   120,   122,   120,   123,   120,   124,
   120,   125,   120,   126,   120,   120,   120,   127,   128,   128,
   129,   130,   130,   131,   131,   132,   133,   133,   134,   134,
   134,   134,   134,   134,   135,   135,   136,   136,   137,   137,
   138,   138,   138,   139,   139,   140,   140,   141,   141,   143,
   142,   142,   142,   145,   144,   146,   146,   147,   148,   148,
   149,   149,   149,   149
};

static const short yyr2[] = {     0,
     1,     2,     0,     1,     1,     1,     1,     0,     7,     2,
     0,     0,     7,     2,     0,     3,     1,     1,     3,     3,
     2,     2,     0,     0,     3,     1,     0,     3,     2,     0,
     0,     4,     2,     1,     1,     0,     0,     3,     0,     5,
     2,     2,     0,     1,     1,     1,     1,     2,     2,     2,
     2,     1,     1,     2,     2,     0,     1,     2,     2,     0,
     1,     0,     1,     0,     2,     3,     3,     2,     0,     2,
     2,     0,     0,     3,     2,     0,     1,     1,     1,     1,
     1,     1,     1,     3,     2,     0,     2,     1,     6,     2,
     0,     5,     7,     7,     1,     2,     1,     2,     1,     2,
     2,     2,     1,     0,     3,     0,     3,     0,     3,     0,
     3,     0,     3,     0,     3,     1,     1,     2,     3,     0,
     2,     3,     0,     2,     1,     2,     2,     0,     1,     1,
     1,     1,     1,     1,     3,     1,     1,     1,     3,     1,
     1,     1,     1,     1,     1,     1,     2,     3,     2,     0,
     4,     1,     1,     0,     5,     1,     0,     2,     3,     0,
     1,     1,     1,     1
};

static const short yydefact[] = {     3,
    44,    45,    46,    47,    62,    64,    60,    56,     0,     0,
    52,     1,     3,     6,     7,     4,    17,    18,     0,     5,
    69,    61,    48,    63,    49,    57,    62,    64,    51,    53,
    62,    64,    50,     8,    12,     2,    24,     0,    23,     0,
    65,     0,    58,    59,    54,    55,    24,     0,    19,     0,
    20,    66,    30,    16,     0,    21,    73,    68,    72,     0,
    11,    15,    27,     0,    25,    26,    22,    76,    69,    70,
     0,     0,     0,     0,     0,     0,     0,     0,   146,   161,
   162,   163,   164,     0,    86,    88,   150,    83,     0,    67,
    78,    77,    79,    80,    81,    82,     0,   103,   120,   123,
   125,   128,   136,   140,   145,   144,   152,   153,     0,    11,
     0,    15,     0,    31,     0,    29,     0,    74,    71,     0,
     0,     0,    99,    98,     0,     0,     0,     0,   101,   154,
   124,   145,    86,     0,     0,    87,     0,   118,     0,   121,
   133,   134,   130,   132,   129,   131,   137,   138,   126,     0,
     0,   141,   142,   143,     0,   114,   110,   112,   106,   108,
   104,   116,   117,     0,     0,   102,   147,     0,    10,     0,
    14,    28,     0,    37,    33,    75,     0,   100,     0,    97,
    95,     0,     0,     0,   157,    85,    84,     0,   120,   123,
   127,   135,   139,     0,     0,     0,     0,     0,     0,     0,
   149,     9,    13,    36,     0,     0,     0,     0,    96,     0,
   160,     0,   156,   151,   119,   122,   115,   111,   113,   107,
   109,   105,   148,    37,    32,    34,    35,    38,    91,    92,
     0,     0,     0,   158,   155,     0,     0,    89,     0,     0,
   160,     0,    90,    93,    94,   159,    43,     0,     0,    41,
    40,    42,     0,     0,     0
};

static const short yydefgoto[] = {   253,
    12,    13,    14,    48,   109,    15,    50,   111,    88,    17,
    18,    38,    56,    39,    53,    65,   113,    66,   116,   173,
   225,   175,   205,   227,   236,   248,   250,    89,    33,    29,
    23,    25,    20,    21,    41,    42,    58,    70,    59,    68,
   118,   133,    91,   134,    92,    93,   238,    94,   182,    95,
   124,    96,    97,   166,   199,   197,   198,   195,   196,   194,
    98,   138,    99,   140,   100,   101,   149,   150,   102,   151,
   103,   155,   104,   105,   167,   106,   135,   107,   185,   212,
   213,   234,   108
};

static const short yypact[] = {   191,
-32768,-32768,-32768,-32768,     8,    15,    21,    41,     0,     1,
-32768,-32768,   191,-32768,-32768,-32768,-32768,-32768,     9,-32768,
   145,-32768,-32768,-32768,-32768,-32768,     8,    15,-32768,-32768,
     8,    15,-32768,    24,    24,-32768,   -15,    -6,    24,    36,
-32768,    16,-32768,-32768,-32768,-32768,-32768,    35,-32768,    40,
-32768,-32768,   -24,-32768,    38,-32768,-32768,-32768,    39,   162,
   222,   222,-32768,   -21,-32768,-32768,-32768,    42,   145,-32768,
    46,    74,    75,    -7,    47,    51,   162,    57,    54,-32768,
-32768,-32768,-32768,     4,   162,-32768,-32768,-32768,    24,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,    59,-32768,    80,    87,
-32768,   197,    20,-32768,   150,-32768,-32768,-32768,    62,   222,
    71,   222,     4,-32768,    94,-32768,    72,-32768,-32768,     4,
    24,    24,-32768,-32768,    76,     4,    77,   116,-32768,-32768,
-32768,   -50,   162,    79,     4,-32768,     4,-32768,     4,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    48,
    48,-32768,-32768,-32768,    48,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,     4,   111,-32768,-32768,    82,-32768,    83,
-32768,-32768,    81,-32768,-32768,-32768,    84,-32768,    93,-32768,
-32768,     4,    85,    96,     4,-32768,-32768,    98,    80,    87,
    11,    20,-32768,     4,     4,     4,     4,     4,     4,   101,
-32768,-32768,-32768,   107,   110,   162,   162,   105,-32768,     4,
   134,   144,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   152,-32768,-32768,-32768,-32768,   178,-32768,
     4,   148,     4,-32768,-32768,   156,   162,-32768,   153,   155,
   134,   190,-32768,-32768,-32768,-32768,   160,   164,   190,-32768,
-32768,-32768,   223,   224,-32768
};

static const short yypgoto[] = {-32768,
   234,-32768,-32768,-32768,   126,-32768,-32768,   125,     3,-32768,
-32768,   -26,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    44,-32768,-32768,-32768,     2,-32768,     5,-32768,-32768,
    12,    14,-32768,-32768,-32768,   180,-32768,-32768,-32768,-32768,
-32768,   -60,-32768,   117,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   -73,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
  -116,    63,   118,    64,   -78,-32768,-32768,-32768,   103,-32768,
   106,-32768,   104,   -82,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    17,-32768
};


#define	YYLAST		259


static const short yytable[] = {    90,
   125,   132,    16,   177,    19,   131,   114,    49,    51,   179,
   164,    22,    55,    63,   165,    16,   128,    19,    24,    79,
    80,    81,    82,    83,    26,    40,    34,    35,    27,    28,
    79,    80,    81,    82,    83,    37,    64,   132,    43,   172,
   115,    44,    45,   132,    30,    46,    84,    52,    31,    32,
    47,   123,    54,   183,   132,    87,   132,    84,   147,   148,
   190,   188,    57,   110,   112,   208,    87,   132,   132,   152,
   153,   154,   132,    40,    79,    80,    81,    82,    83,    60,
     1,     2,     3,     4,     5,     6,     7,     8,    72,    73,
   200,    61,    11,   232,    49,    51,    62,    67,    69,   132,
   121,   122,   117,    79,    80,    81,    82,    83,   120,   126,
    87,   211,   110,   127,   112,   129,   130,   136,   137,   168,
   217,   218,   219,   220,   221,   222,   139,   132,   170,   181,
    84,   174,   184,   176,   178,   180,   187,   201,   228,    87,
   202,   203,   204,   209,   224,   229,   230,   206,     1,     2,
     3,     4,     5,     6,     7,     8,   207,   239,   210,   241,
    11,   214,   223,   231,    71,     1,     2,     3,     4,     5,
     6,     7,     8,    72,    73,    74,   243,    11,    75,    76,
    77,    78,   156,   157,   158,   159,   160,   161,    79,    80,
    81,    82,    83,   233,     1,     2,     3,     4,     5,     6,
     7,     8,     9,    10,   162,   163,    11,   235,   -39,   237,
   164,   240,   242,   245,   165,    84,   244,   247,    85,   249,
    86,   251,   254,   255,    87,     1,     2,     3,     4,     5,
     6,     7,     8,    72,    73,   169,   171,    11,   141,   142,
   143,   144,   145,   146,   147,   148,    36,   226,   119,   186,
   252,   215,   191,   216,   189,     0,   192,   246,   193
};

static const short yycheck[] = {    60,
    74,    84,     0,   120,     0,    84,    28,    34,    35,   126,
    61,     4,    39,    38,    65,    13,    77,    13,     4,    27,
    28,    29,    30,    31,     4,    21,    27,    27,     8,     9,
    27,    28,    29,    30,    31,    27,    61,   120,    27,   113,
    62,    28,    31,   126,     4,    32,    54,    63,     8,     9,
    27,    59,    59,   127,   137,    63,   139,    54,    48,    49,
   139,   135,    27,    61,    62,   182,    63,   150,   151,    50,
    51,    52,   155,    69,    27,    28,    29,    30,    31,    64,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
   164,    57,    16,   210,   121,   122,    57,    60,    60,   182,
    27,    27,    61,    27,    28,    29,    30,    31,    63,    63,
    63,   185,   110,    63,   112,    59,    63,    59,    39,    58,
   194,   195,   196,   197,   198,   199,    40,   210,    58,   127,
    54,    38,    17,    62,    59,    59,    58,    27,    29,    63,
    59,    59,    62,    59,    38,   206,   207,    64,     4,     5,
     6,     7,     8,     9,    10,    11,    64,   231,    63,   233,
    16,    64,    62,    59,     3,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    13,    14,   237,    16,    17,    18,
    19,    20,    33,    34,    35,    36,    37,    38,    27,    28,
    29,    30,    31,    60,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    55,    56,    16,    64,    57,    32,
    61,    64,    57,    59,    65,    54,    64,    28,    57,    60,
    59,    58,     0,     0,    63,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    13,   110,   112,    16,    42,    43,
    44,    45,    46,    47,    48,    49,    13,   204,    69,   133,
   249,   189,   150,   190,   137,    -1,   151,   241,   155
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 8:
#line 75 "parser.y"
{ insert_type(); ;
    break;}
case 12:
#line 80 "parser.y"
{ insert_type(); ;
    break;}
case 24:
#line 104 "parser.y"
{ insert_type(); ;
    break;}
case 27:
#line 106 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 31:
#line 113 "parser.y"
{insert_dimensions();;
    break;}
case 37:
#line 122 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 38:
#line 122 "parser.y"
{ insert_value(); ;
    break;}
case 39:
#line 125 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 66:
#line 159 "parser.y"
{strcpy(current_function,current_id); insert_type();;
    break;}
case 73:
#line 175 "parser.y"
{ insert_params(); insert_type(); ;
    break;}
case 104:
#line 230 "parser.y"
{strcpy(previous_operator,"=");;
    break;}
case 106:
#line 231 "parser.y"
{strcpy(previous_operator,"+=");;
    break;}
case 108:
#line 232 "parser.y"
{strcpy(previous_operator,"-=");;
    break;}
case 110:
#line 233 "parser.y"
{strcpy(previous_operator,"*=");;
    break;}
case 112:
#line 234 "parser.y"
{strcpy(previous_operator,"/=");;
    break;}
case 114:
#line 235 "parser.y"
{strcpy(previous_operator,"%=");;
    break;}
case 129:
#line 264 "parser.y"
{strcpy(previous_operator,">=");;
    break;}
case 130:
#line 265 "parser.y"
{strcpy(previous_operator,"<=");;
    break;}
case 131:
#line 266 "parser.y"
{strcpy(previous_operator,">");;
    break;}
case 132:
#line 267 "parser.y"
{strcpy(previous_operator,"<");;
    break;}
case 133:
#line 268 "parser.y"
{strcpy(previous_operator,"==");;
    break;}
case 134:
#line 269 "parser.y"
{strcpy(previous_operator,"!=");;
    break;}
case 150:
#line 298 "parser.y"
{strcpy(previous_operator,"(");;
    break;}
case 154:
#line 302 "parser.y"
{strcpy(previous_operator,"(");;
    break;}
case 161:
#line 315 "parser.y"
{ insert_value(); ;
    break;}
case 162:
#line 316 "parser.y"
{ insert_value(); ;
    break;}
case 163:
#line 317 "parser.y"
{ insert_value(); ;
    break;}
case 164:
#line 318 "parser.y"
{ insert_value(); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 320 "parser.y"


extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insert_SymbolTable_type(char *,char *);
void insert_SymbolTable_value(char *, char *);
void insert_ConstantTable(char *, char *);
void insert_SymbolTable_arraydim(char *, char *);
void insert_SymbolTable_functionparam(char *, char *);
void printSymbolTable();
void printConstantTable();


int main()
{	
	yyparse();
	printf("------------------------------------------------------------------------------------------------\n");
	printf("%30s SYMBOL TABLE \n", " ");
	printf("------------------------------------------------------------------------------------------------\n");
	printSymbolTable();

	printf("------------------------------------------------------------------------------------------------\n");
	
	
	printf("------------------------------------------------------------------------------------------------\n");
	printf("%30s CONSTANT TABLE \n", " ");
	printf("-------------------------------------------------------------------------------------------------\n");
	printConstantTable();
	printf("------------------------------------------------------------------------------------------------\n");


}

void yyerror(char *s)
{
	printf("Line No. : %d %s %s\n",yylineno, s, yytext);
	printf("INVALID PARSE\n");
	
}

void insert_type()
{
	insert_SymbolTable_type(current_id,current_type);
}

void insert_value()
{	
	if(strcmp(previous_operator, "=") == 0)
	{	insert_SymbolTable_value(current_id,current_value);
	}
}	

void insert_dimensions()
{
    insert_SymbolTable_arraydim(current_id, current_value);
}

void insert_params()
{
    insert_SymbolTable_functionparam(current_function, current_id);
}

int yywrap()
{
	return 1;
}